"""Quizzes: Hobbes through the keep-going maps."""
from course_helpers import mc, tf, ms, make_quiz


def all_quizzes():
    q = {}

    def add(aid, title, intro, *questions):
        q[aid] = make_quiz(aid, title, intro, list(questions))

    add(
        "hobbes-state-of-nature",
        "After Leviathan 13–14",
        "War from equality, not from cartoon vice.",
        mc(1, "Hobbes’s war of all against all is driven, in these chapters, mainly by",
           "a few monstrous villains",
           "equality of vulnerability plus the right of nature to what one judges needful — which makes preemption rational",
           "original sin as in Augustine",
           "Aristotle’s natural slave thesis",
           "b",
           "LookFor: equality, not vice, as the engine. Competition, diffidence, glory are the three causes of quarrel."),
        mc(2, "The right of nature differs from a law of nature in that",
           "they are the same word",
           "right is liberty to use power; law is a precept that binds (seek peace; be willing to lay down right when others do)",
           "law exists only after a sovereign, so chapter 14 cannot mention it",
           "right is identical with justice",
           "b",
           "Injustice as breaking covenant waits on a power to enforce. The laws of nature are still precepts of reason in 14."),
        mc(3, "A covenant, here, needs a sword because",
           "Hobbes likes weapons",
           "words alone do not bind where there is no common power to punish — covenants without the sword are but words",
           "the state of nature already has courts",
           "property is innate",
           "b",
           "That is why the sitting points to chapters 17–21 next."),
        tf(4, "On this account there can already be injustice, in the full civil sense, before a sovereign.",
           "false",
           "Where there is no common power, there is no law in the sense that makes injury a crime. That is Hobbes’s sting."),
    )
    add(
        "hobbes-sovereign",
        "After Leviathan 17–18 and 21",
        "Authorization, and the liberty that remains.",
        mc(1, "The commonwealth is generated when",
           "the strongest seizes grain",
           "each authorizes one person or assembly to bear their person — a real unity, not a mere crowd",
           "the Church crowns a king only",
           "Locke’s property theory is assumed",
           "b",
           "Authorization and representation are the legal-metaphysical move, not only fear."),
        mc(2, "The sovereign’s rights, in ch. 18, include that subjects",
           "may lawfully split sovereignty whenever they dislike a tax",
           "cannot accuse the sovereign of injustice in the covenant’s terms — they have authorized the acts",
           "retain a private right to all things as in ch. 13",
           "must be Christians by definition",
           "b",
           "A common misreading is ‘might makes right’ without the authorization story."),
        mc(3, "True liberty of subjects in ch. 21 is, for Hobbes,",
           "a natural right to everything remaining after the covenant",
           "the silence of the law — plus the inalienable right to defend one’s life",
           "democratic participation as a natural right",
           "the right to abolish the sovereign at will without contradiction",
           "b",
           "The sitting: what liberty remains. It is not a liberal bill of rights avant la lettre."),
    )
    add(
        "locke-property",
        "After Second Treatise (assigned chapters)",
        "Labor, consent, and when government dissolves.",
        mc(1, "Property in the state of nature, for Locke, begins in",
           "the sovereign’s grant only",
           "mixing labor with what is common, within the spoilage limit and (later) the invention of money",
           "Hobbes’s right to everything",
           "inheritance from Adam as Filmer has it, without labor",
           "b",
           "Ch. 5 is the labor theory and its provisos. Do not skip the limits."),
        mc(2, "Political society is made by",
           "conquest alone, always",
           "consent to form a community that may then use majority to settle the government — not tacit remaining under a conqueror as if that were enough",
           "divine right of kings as the only title",
           "the war of all against all as Hobbes describes it, without remainder",
           "b",
           "Ch. 8: consent. Compare Hobbes: Locke’s natural condition already has law of nature and property."),
        mc(3, "Government may be dissolved, in the assigned later chapter, when",
           "taxes exist",
           "it acts contrary to the trust — tyranny as exercise of power beyond right",
           "people are equal",
           "there is a legislature",
           "b",
           "Ch. 19: appeal to heaven is not a weekly hobby. It is the right of resistance when trust is broken."),
        tf(4, "Locke’s state of nature is identical with Hobbes’s war of all against all.",
           "false",
           "Locke has a law of nature and property before the magistrate. That is the disagreement the unit is for."),
    )
    add(
        "locke-no-innate",
        "After Essay I.2 (and the assigned anti-innatism)",
        "The blank paper is an argument, not a metaphor only.",
        mc(1, "Locke attacks innate speculative principles because",
           "children already know mathematics",
           "there is no universal consent, and what is later agreed can be explained by teaching and reason — so innateness is idle",
           "Aristotle proved innatism",
           "ideas are all Forms",
           "b",
           "LookFor: no universal consent; learning explains apparent innateness."),
        mc(2, "‘Innate’ would be a useful hypothesis, on his terms, only if",
           "priests say so",
           "the mark were actually in all minds independently of instruction — which he denies we find",
           "Descartes never doubted",
           "language were impossible",
           "b",
           "The sitting is the argumentative burden, not a slogan ‘empiricism.’"),
        tf(3, "Locke thinks we are born with the idea of God stamped on the mind as a letter is stamped on paper.",
           "false",
           "That is the view I.2 is written against. God is known another way, later in the Essay."),
    )
    add(
        "locke-qualities",
        "After Essay II.1, 8, 27 (assigned)",
        "Ideas from experience; primary/secondary; personal identity.",
        mc(1, "All ideas, for Locke here, come from",
           "innate principles",
           "sensation and reflection — experience in two directions",
           "the cogito alone",
           "the sovereign",
           "b",
           "II.1: the fountain. Simple ideas are not made by us at will."),
        mc(2, "Secondary qualities are",
           "in the object just as we sense them, independently of us",
           "powers in bodies to produce sensations (color, taste) that are not resemblances of the body’s bulk, figure, motion",
           "identical with primary qualities",
           "Forms in a separate heaven",
           "b",
           "II.8: the distinction. A common mistake is to think Locke denies that objects cause color-experience."),
        mc(3, "Personal identity, in II.27, is",
           "sameness of soul-substance as such, always",
           "sameness of consciousness — a forensic notion for reward and punishment",
           "sameness of body only",
           "impossible",
           "b",
           "The sitting: consciousness, not a hidden substance, as the person. Thought-experiments of transfer are the method."),
    )
    add(
        "berkeley-principles",
        "After the Principles (introduction and opening)",
        "To be is to be perceived — as an argument.",
        mc(1, "Berkeley’s attack on abstract general ideas (introduction) claims that",
           "we never use general words",
           "we cannot form the idea of a triangle that is neither equilateral nor scalene, etc. — abstraction as Locke describes it is a fiction",
           "Locke never discussed ideas",
           "only God abstracts",
           "b",
           "The introduction is not optional. It undercuts a certain theory of meaning before the ontology."),
        mc(2, "‘Esse is percipi’ for unthinking things means",
           "they exist unperceived as matter",
           "their being is to be perceived (or to perceive, in the case of spirits); matter as inert substratum is idle",
           "only my mind exists (solipsism as his conclusion)",
           "science is impossible",
           "b",
           "He keeps God and other spirits. Idealism here is not ‘only I exist.’"),
        tf(3, "Berkeley thinks the laws of nature cannot be stated because there are no bodies.",
           "false",
           "Ideas occur in regular order — that is nature. He is not discarding physics as a pattern of ideas."),
        mc(4, "A plausible misreading is that Berkeley",
           "denies matter as substratum",
           "claims tables vanish when we blink, with no God to sustain the order of ideas",
           "keeps spirits as substances",
           "attacks abstraction",
           "b",
           "Divine perception (and the stability of laws) is how he avoids the ‘vanishing furniture’ joke."),
    )
    add(
        "hume-enquiry-ideas",
        "After Enquiry §2 (and the assigned origin of ideas)",
        "Copy principle, and a test for meaning.",
        mc(1, "Hume’s copy principle says that",
           "all ideas are innate",
           "simple ideas are copies of impressions; where an alleged idea has no impression, suspect a confusion",
           "impressions copy ideas",
           "God copies our minds",
           "b",
           "The missing shade of blue is the famous apparent exception — note it, don’t let it erase the rule."),
        mc(2, "The principle is used as",
           "a proof of the Forms",
           "a meaning-test: demand the impression from which a philosophical term is copied",
           "a political contract",
           "Berkeley’s esse is percipi restated without change",
           "b",
           "The sitting prepares causation: ‘power’ and ‘necessary connexion’ will be run through this test."),
        tf(3, "Hume thinks complex ideas can never be assembled from simpler ones.",
           "false",
           "The imagination compounds. The discipline is on simple ideas and empty terms."),
    )
    add(
        "hume-enquiry-causation",
        "After Enquiry §§4–5, 7",
        "Custom, not insight into necessity.",
        mc(1, "Matters of fact about the unobserved are, for Hume, founded on",
           "demonstration like geometry",
           "cause and effect — and the inference from observed to unobserved is not itself demonstrative",
           "innate causal forms",
           "the Cartesian God immediately",
           "b",
           "§4: relations of ideas vs matters of fact. The future resembling the past is not a demonstration."),
        mc(2, "Necessary connexion, as we have it, is",
           "an impression of a real glue in objects that the mind reads off",
           "the feeling of determination after custom — an impression of reflection, projected onto the world",
           "identical with Locke’s primary qualities",
           "denied to exist even as a feeling",
           "b",
           "§7: we do not perceive power in the objects. Custom is the guide of life (§5)."),
        mc(3, "Mitigated skepticism here means",
           "believing nothing",
           "limiting inquiry to what custom and experience can support, without a Pyrrhonian refusal to live",
           "returning to innate ideas",
           "proving induction",
           "b",
           "The sitting: Hume is not Sextus. He walks out of the study."),
        tf(4, "Hume thinks we ought to stop making causal inferences.",
           "false",
           "We cannot and should not. The point is what they are, not a ban."),
    )
    add(
        "hume-enquiry-miracles",
        "After Enquiry §10",
        "Testimony vs uniform experience.",
        mc(1, "A miracle, in Hume’s definition here, is",
           "any surprising event",
           "a violation of the laws of nature (as established by uniform experience)",
           "whatever priests report",
           "a relation of ideas",
           "b",
           "Without that definition the argument does not start. Do not substitute a looser sense."),
        mc(2, "The evidential claim is that",
           "miracles never happen, as a metaphysical proof",
           "no testimony is sufficient to establish a miracle unless the falsehood of the testimony would be more miraculous than the fact — and in practice it is not",
           "all religions are equally demonstrated",
           "experience never supports laws of nature",
           "b",
           "It is a rule of evidence, not a laboratory disproof of every report."),
        tf(3, "Section 10 argues from the copy principle alone, without weighing kinds of testimony.",
           "false",
           "The essay is about testimony, passion, and contrary miracles — not only §2."),
    )
    add(
        "hume-treatise-identity",
        "After Treatise I.4.6",
        "The self as a bundle, and a fiction of identity.",
        mc(1, "When Hume looks for a self, he finds",
           "a simple immaterial substance always present",
           "particular perceptions — and no impression of a simple continuing self distinct from them",
           "the cogito as Descartes left it",
           "Locke’s forensic person as a substance",
           "b",
           "The bundle is a report of introspection plus an account of why we feign identity."),
        mc(2, "We ascribe identity to the mind because",
           "we perceive a soul-atom",
           "imagination associates resembling, related perceptions and mistakes succession for one object",
           "the Church requires it",
           "Berkeley proved spirits only",
           "b",
           "LookFor: the fiction, not a joke about ‘no one is home.’ Agency and morals wait on later books; this sitting is I.4.6."),
        tf(3, "Hume claims that personal identity is a demonstrated metaphysical truth like a triangle’s.",
           "false",
           "It is a natural belief explained, not a relation of ideas."),
    )
    add(
        "hume-dialogues-design",
        "After the Dialogues (assigned parts)",
        "Design, analogy, and what we may infer.",
        mc(1, "The design argument, as Cleanthes urges, infers a designer from",
           "a priori necessity like Demea’s",
           "order and adjustment in nature as like a machine, hence a mind like a human artisan, proportioned to the effect",
           "the ontological argument",
           "revelation only",
           "b",
           "Analogy is the engine. Philo will press the disanalogy."),
        mc(2, "Philo’s pressure includes that",
           "there is no order in nature at all",
           "the analogy underdetermines: many causes could produce order; the inference to a unique, infinite, moral author outruns the data",
           "Cleanthes is not a character",
           "science forbids all analogical reasoning",
           "b",
           "The sitting: what the assigned parts allow you to conclude — not a biography of Hume."),
        mc(3, "A student who thinks the Dialogues simply ‘prove atheism’ has",
           "quoted Philo’s whole last word without remainder",
           "missed the dramatic underdetermination and the lingering natural belief in order — the text is not a tract",
           "finished Demea’s a priori proof",
           "repeated Enquiry §10 only",
           "b",
           "LookFor was the argument’s limits, not a label."),
    )
    add(
        "rousseau-inequality",
        "After the Discourse on Inequality (assigned part)",
        "Natural independence, and what society adds.",
        mc(1, "Natural man, in this discourse’s conjecture, is marked by",
           "Hobbesian war as the original fact",
           "limited needs, pity, and independence — inequality as we know it is largely social and historical",
           "innate property in land",
           "the general will already voting",
           "b",
           "The sitting: a genealogy of inequality, not a field report. Distinguish natural from moral/political inequality."),
        mc(2, "Amour-propre (in the story of socialization) differs from amour de soi in that",
           "they are the same",
           "it is comparative self-love that needs others’ eyes — a social passion, not mere self-preservation",
           "it is identical with pity",
           "only aristocrats have it",
           "b",
           "A common mix-up is to treat all self-love as vice. Rousseau splits the kinds."),
        tf(3, "Rousseau claims the historical state of nature is a documented ethnography of one tribe.",
           "false",
           "He says we must conjecture. The method is hypothetical history."),
    )
    add(
        "rousseau-contract-i",
        "After Social Contract I",
        "Freedom, and the strange alienation that saves it.",
        mc(1, "Man is born free, and everywhere in chains: the book’s problem is",
           "how to return to the forests",
           "what could make that subjection legitimate — a form of association that defends each while leaving each as free as before",
           "how to maximize Hobbes’s sovereign",
           "how to abolish all law",
           "b",
           "I.6: the fundamental problem. Legitimacy, not a travel memoir."),
        mc(2, "Total alienation to the whole, on Rousseau’s terms, is supposed to",
           "create a master distinct from the citizens",
           "produce a moral/collective body whose general will is one’s own in the civil state",
           "restore the right of the strongest as such",
           "be a sales contract for one’s labor only",
           "b",
           "The sitting: why this is not Hobbes’s authorization of a person apart. You may still object that it is."),
        tf(3, "Book I treats the right of the strongest as a sufficient title to political authority.",
           "false",
           "He rejects force as right. That is the clearing for the compact."),
    )
    add(
        "rousseau-contract-ii",
        "After Social Contract II",
        "General will, and the lawgiver’s paradox.",
        mc(1, "The general will is directed to",
           "the sum of private appetites (will of all) as such",
           "the common interest — it can be mistaken in deliberation but is not defined as a poll of factions",
           "whatever the monarch dreams",
           "natural pity only",
           "b",
           "II.3: will of all vs general will. A common error is to equate them."),
        mc(2, "Sovereignty, here, is",
           "alienable to a representative who then owns it",
           "the exercise of the general will, inalienable and indivisible in the sense Rousseau argues",
           "identical with government as a specialist executive, full stop",
           "property in land",
           "b",
           "Distinguish sovereignty from government — a lookFor in this sitting."),
        mc(3, "The lawgiver is a paradox because",
           "laws are unnecessary",
           "a people that needs forming is not yet able to will the laws that would form it — so a founder speaks a wisdom the people cannot yet originate",
           "Rousseau forbids all founders",
           "only God legislates in Book II with no remainder",
           "b",
           "II.7: take the paradox seriously. It is not a footnote about Lycurgus trivia."),
    )
    add(
        "smith-moral-sentiments",
        "After TMS I.i (and the assigned opening)",
        "Sympathy, and the impartial spectator in seed.",
        mc(1, "Sympathy, for Smith here, is",
           "pity only for the poor",
           "a fellow-feeling produced by imagining ourselves in another’s situation — the basis of moral sentiment",
           "Hobbesian glory",
           "a utilitarian calculus already complete",
           "b",
           "The sitting: moral life begins in spectatorship, not in a lonely law."),
        mc(2, "We judge others’ feelings by",
           "whether they maximize our wealth",
           "whether we can go along with them — propriety as correspondence of sentiment",
           "innate Cartesian ideas",
           "the general will voting",
           "b",
           "Propriety is the first tool. The impartial spectator develops from this social mirroring."),
        tf(3, "Smith’s opening treats self-interest as the only motive, as a certain reading of the Wealth of Nations might suggest.",
           "false",
           "TMS begins in sympathy. Do not import a cartoon ‘economic man’ into I.i."),
    )
    add(
        "kant-cpr-prefaces",
        "After the first Critique prefaces (and assigned intro)",
        "The Copernican turn as a research program.",
        mc(1, "Kant’s Copernican analogy proposes that",
           "the earth is the center of knowledge",
           "objects conform to our way of knowing (space, time, categories), rather than the mind copying things in themselves",
           "Hume is simply mistaken about custom",
           "metaphysics is impossible in every sense",
           "b",
           "The sitting: a hypothesis for how a priori knowledge of objects is possible. Not a weather report."),
        mc(2, "The Critique limits knowledge to",
           "things in themselves as given",
           "appearances (phenomena) — while still making room for faith regarding what cannot be known theoretically",
           "psychology only",
           "Lockean secondary qualities only",
           "b",
           "Bxxx: I had to deny knowledge to make room for faith. Keep the two-object / two-aspect caution as the assigned intro frames it."),
        mc(3, "Hume’s role in this preface-story is that",
           "he is ignored",
           "he interrupted dogmatic metaphysics — the Critique is a response that saves necessity by relocating it",
           "he already stated the categories",
           "he proved God",
           "b",
           "You were prepared by the Enquiry. Kant names the interruption."),
        tf(4, "The Copernican turn means astronomy replaces epistemology.",
           "false",
           "It is an analogy about who conforms to whom in cognition."),
    )
    add(
        "kant-groundwork-i",
        "After Groundwork I",
        "The good will, and duty’s contrast with inclination.",
        mc(1, "The good will is good",
           "only because of what it achieves",
           "without qualification — even if it achieves nothing, unlike talents and gifts of fortune",
           "when it maximizes pleasure",
           "only in a holy being, never in us",
           "b",
           "The opening thesis. Talents can be bad without a good will."),
        mc(2, "An action has moral worth, in Section I’s shopkeeper contrast, when",
           "it accords with duty and is done from immediate inclination only",
           "it is done from duty, not merely in accordance with duty",
           "it produces the best consequences",
           "the agent feels nothing",
           "b",
           "LookFor: from duty vs in accordance with duty. The honest shopkeeper is the famous case."),
        tf(3, "Kant thinks a person without any inclination toward the good cannot act from duty.",
           "false",
           "If anything, the analysis isolates duty more clearly when inclination does not already pull the same way — though the text is subtler than a cartoon of joyless duty."),
        mc(4, "The first formulation you meet in this sitting’s trajectory is that of",
           "the difference principle",
           "acting on a maxim that you can will as universal law (the section’s argument toward the categorical imperative)",
           "the greatest happiness of the greatest number",
           "the right of nature",
           "b",
           "Section I arrives at the CI from common moral cognition. Section II will unpack formulas."),
    )
    add(
        "kant-groundwork-ii",
        "After Groundwork II (and the assigned stretch of III if included)",
        "Formulas of the categorical imperative.",
        mc(1, "A hypothetical imperative is",
           "unconditional",
           "conditional on an end you already will — a means-end rule",
           "the moral law",
           "impossible",
           "b",
           "The CI is not hypothetical. That contrast is the grammar of Section II."),
        mc(2, "The formula of humanity requires that you",
           "use persons as mere means whenever convenient",
           "treat humanity in yourself and others always as an end, never merely as a means",
           "maximize aggregate pleasure",
           "obey the sovereign as Hobbes’s authorization",
           "b",
           "LookFor: not a slogan. False promising and the ‘mere means’ test were the sitting’s work."),
        mc(3, "Autonomy, here, is",
           "doing whatever you feel",
           "the will’s property of being a law to itself — the third formula’s kingdom of ends gathers legislators",
           "heteronomy by inclination renamed",
           "Spinoza’s necessity",
           "b",
           "Heteronomy is when the law comes from an object of desire or an external authority as such."),
        tf(4, "Kant thinks the moral law is a piece of advice based on what typically makes people happy.",
           "false",
           "That would be a hypothetical imperative of prudence, not a categorical one."),
    )
    add(
        "hegel-lordship",
        "After the lordship/bondage sitting",
        "Self-consciousness that needs another.",
        mc(1, "The struggle to the death is about",
           "land reform",
           "recognition: each self-consciousness wants to be acknowledged as not a mere thing",
           "Epicurean pleasure",
           "Hume’s custom",
           "b",
           "The sitting: desire and recognition, not a war movie. Life is staked because a life without recognition is not yet self-consciousness."),
        mc(2, "The lord’s position is unstable because",
           "he works too much",
           "he depends on the bondsman and on a recognition that, coming from a reduced other, cannot satisfy",
           "Hegel prefers slavery as a final truth",
           "there is no dialectic",
           "b",
           "The twist: the working consciousness finds itself in the formed thing. Do not stop at ‘master wins.’"),
        tf(3, "Independent self-consciousness, on this account, is achieved by ignoring others.",
           "false",
           "It is essentially social. That is the break with a lonely cogito as the whole story."),
    )
    add(
        "schopenhauer-will",
        "After The World as Will (assigned books)",
        "Representation, and will as the inner of phenomena.",
        mc(1, "The world as representation is",
           "the will itself directly",
           "object for a subject — Kant’s phenomena radicalized; the thing in itself is named will",
           "a Lockean blank paper",
           "Hegel’s Absolute as a committee",
           "b",
           "Book I: the world is my representation. Book II: will as the kernel."),
        mc(2, "Will, in the assigned stretch, is",
           "a rational planner like Kant’s good will",
           "blind striving that objectifies in nature and in us — intellect is its instrument, not its master",
           "identical with the categorical imperative",
           "a social contract",
           "b",
           "LookFor: not moral will. Metaphysical will. Art and denial of the will are later therapy, if your sitting reached them."),
        tf(3, "Schopenhauer thinks sufficient reason explains the will as it does objects in representation.",
           "false",
           "The will as thing in itself is precisely not an object in the principle of sufficient reason’s net — that is the Kantian inheritance twisted."),
    )
    add(
        "mill-utilitarianism",
        "After Utilitarianism ch. 2",
        "Quality of pleasure, and the competent judges.",
        mc(1, "Mill’s utilitarianism takes as the standard",
           "the agent’s own pleasure only",
           "happiness as pleasure and absence of pain — of all concerned, with a distinction of higher and lower pleasures",
           "Kant’s good will",
           "the right of the strongest",
           "b",
           "Ch. 2: not a cartoon of swine. Quality is the point of the sitting."),
        mc(2, "Higher pleasures are identified by",
           "priests",
           "the preference of competent judges who have experienced both kinds",
           "intensity alone",
           "the Forms",
           "b",
           "A common misreading is that Mill simply asserts poetry is nicer. The test is comparative verdict of the competent."),
        tf(3, "Mill claims a dissatisfied Socrates is not more worthy than a satisfied fool, because quantity of pleasure is all.",
           "false",
           "The famous line goes the other way: better Socrates dissatisfied. That is quality."),
        mc(4, "‘Greatest happiness’ as Mill states it is not",
           "impartial among persons in the theory’s intent",
           "a license for the agent to count only a private clique’s pleasures as the whole of the standard",
           "a contrast with Kantian duty as motive",
           "compatible with higher pleasures",
           "b",
           "The standard is the general happiness. Motive may still be local; that is a distinction Mill himself draws."),
    )
    add(
        "mill-liberty-harm",
        "After On Liberty I–II",
        "The harm principle, and free discussion.",
        mc(1, "The harm principle says that",
           "the state may coerce to make you virtuous for your own good as such",
           "the only purpose for which power may be rightfully exercised over a member of a civilized community, against his will, is to prevent harm to others",
           "all speech is harm",
           "custom is the highest law",
           "b",
           "Ch. 1: not a small slogan. Paternalism is the target."),
        mc(2, "Mill defends freedom of discussion because",
           "all opinions are equally true",
           "silencing an opinion robs the human race — if right, of truth; if wrong, of a clearer collision with error",
           "the Church is always correct",
           "harm never comes from speech",
           "b",
           "Ch. 2: three cases (true, false, mixed). LookFor was the argument, not ‘be nice.’"),
        tf(3, "On Liberty I treats self-regarding faults as properly punished by the magistrate as crimes.",
           "false",
           "The split self-regarding / other-regarding is the point of the principle — with all the difficulties you were asked to feel."),
    )
    add(
        "mill-liberty-individuality",
        "After On Liberty III",
        "Individuality as a good, not a mood.",
        mc(1, "Individuality matters, for Mill, because",
           "eccentricity is always morally better than virtue",
           "human capacities develop by choice and experiments in living — a social good, not only a private taste",
           "custom is infallible",
           "the harm principle is repealed",
           "b",
           "Ch. 3: genius and originality as conditions of progress. Not a teenage manifesto."),
        mc(2, "The despotism of custom is dangerous because",
           "customs never work",
           "it freezes a type and prevents the competition of ways of life that progress requires",
           "Kant forbade custom",
           "only aristocrats have selves",
           "b",
           "The sitting: why liberty is not only non-interference with trade."),
        tf(3, "Mill thinks a person should never consider others’ well-being when choosing a way of life.",
           "false",
           "The harm principle still binds. Individuality is not a right to injure."),
    )
    add(
        "kierkegaard-fear",
        "After Fear and Trembling (assigned)",
        "Abraham, and a suspension that is not ethics as usual.",
        mc(1, "The teleological suspension of the ethical names",
           "a permission to murder for convenience",
           "Abraham’s relation to Isaac as not justifiable in universal ethical terms — a private absolute duty to God",
           "Hegel’s lordship",
           "Kant’s CI as Abraham’s maxim",
           "b",
           "The sitting: the knight of faith vs the tragic hero who remains in the ethical."),
        mc(2, "Why Abraham cannot speak, on this reading, is that",
           "he is shy",
           "the ordeal cannot be translated into the universal without ceasing to be faith — language is the ethical’s medium",
           "Hebrew had no words",
           "Johannes de Silentio is a historian",
           "b",
           "Silence is a philosophical claim about the incommensurable, not a plot device only."),
        tf(3, "Fear and Trembling presents Abraham as a Hegelian ethical exemplar of family life.",
           "false",
           "The whole point is the collision with the ethical universal."),
    )
    add(
        "marx-manifesto",
        "After Manifesto I–II",
        "History as class struggle, and a program.",
        mc(1, "The history of hitherto existing society is, in the Manifesto’s opening claim,",
           "a history of ideas only",
           "the history of class struggles",
           "a social contract",
           "natural inequality as Rousseau’s forests",
           "b",
           "Bourgeois and proletarian is the modern simplification of that history."),
        mc(2, "The bourgeoisie is revolutionary, on this account, because",
           "it conserves feudal relations",
           "it constantly revolutionizes production and draws the whole world into its mode — and so produces its own grave-diggers",
           "it abolishes classes immediately in 1848",
           "it restores the guilds",
           "b",
           "LookFor: the double movement. Praise of bourgeois dynamism is not a slip."),
        mc(3, "Section II’s communism is presented as",
           "a return to primitive scarcity as an ideal",
           "an abolition of bourgeois property as class property — not of all personal appropriation as such, in the pamphlet’s rhetoric",
           "identical with Kant’s kingdom of ends",
           "a defense of the absolute monarch",
           "b",
           "Read the charges and replies. Do not substitute a later textbook for the pamphlet’s sentences."),
        tf(4, "The Manifesto treats the state as a neutral referee above classes.",
           "false",
           "Political power is organized power of one class for oppressing another — in this text’s terms."),
    )
    add(
        "nietzsche-genealogy-i",
        "After Genealogy I",
        "Good/bad, and the slave revolt in morals.",
        mc(1, "Noble good/bad, in Essay I, contrasts with",
           "the same as good/evil",
           "good/evil as the resentful inversion that makes the strong ‘evil’ and the weak ‘good’",
           "Kant’s CI",
           "Mill’s competent judges",
           "b",
           "LookFor: two pairs of terms. Mixing them is the usual mistake."),
        mc(2, "Ressentiment is creative in the slave revolt because",
           "it invents nothing",
           "it produces a new valuation — a spiritual revenge — rather than a mere complaint",
           "it is identical with pity as Smith describes it",
           "it restores Homeric excellence unchanged",
           "b",
           "The sitting: morality has a history and a psychology. Not a refutation by insult."),
        tf(3, "Nietzsche’s first essay is mainly a biography of Jesus as a historical individual.",
           "false",
           "It is a typology of valuation (with a notorious closing on the ‘Redeemer’). Stay with the good/evil mechanism."),
    )
    add(
        "nietzsche-genealogy-ii",
        "After Genealogy II",
        "Conscience, debt, and the badly remembered animal.",
        mc(1, "The promise-making animal requires",
           "forgetting as a force, and a memory of the will — a history of pain as mnemonics",
           "innate categorical imperatives",
           "a social contract in Hobbes’s exact sense",
           "the Forms",
           "a",
           "LookFor: memory, pain, and the right to make promises. Bad conscience is a later internalization."),
        mc(2, "Bad conscience arises, on this story, when",
           "people learn algebra",
           "instincts that cannot discharge outwardly turn inward — the soul’s interior as a result, not a given",
           "Kant publishes the Groundwork",
           "the nobles invent justice",
           "b",
           "Internalization is the genealogical claim. Guilt as debt is the linguistic-legal thread."),
        tf(3, "Essay II treats guilt as a timeless fact of reason with no history.",
           "false",
           "The whole essay is the history. That is the method you were assigned."),
    )
    add(
        "nietzsche-gay-science",
        "After the Gay Science (assigned)",
        "The death of God as an event in meaning.",
        mc(1, "‘God is dead’ in the assigned stretch is primarily",
           "a meteorological report",
           "a claim that the Christian-Platonic horizon of meaning has collapsed — with consequences we have not yet absorbed",
           "a proof that no one ever believed",
           "identical with Hume’s §10 only",
           "b",
           "The madman is about the event’s unreadiness, not a joke at priests only."),
        mc(2, "A philosophical task this sitting names is",
           "returning to Burnet’s Milesians as sufficient",
           "what values and sciences still presuppose the dead God — and what cheerfulness or weight that implies",
           "restoring the slave revolt",
           "proving the Five Ways",
           "b",
           "LookFor was the diagnosis, not a Wikipedia timeline of Nietzsche’s life."),
        tf(3, "The Gay Science sitting is mainly a system of metaphysics like the Monadology.",
           "false",
           "It is aphoristic diagnosis. The quiz checks the event, not a table of categories."),
    )
    add(
        "peirce-ideas-clear",
        "After ‘How to Make Our Ideas Clear’",
        "Belief as a habit, and the pragmatic maxim.",
        mc(1, "For Peirce here, belief is",
           "a private feeling with no effects",
           "a habit of action — doubt is the irritation that inquiry tries to settle",
           "innate Cartesian clarity",
           "identical with a Form",
           "b",
           "The paper’s psychology of inquiry is the setup for the maxim."),
        mc(2, "The pragmatic maxim says that the meaning of a conception lies in",
           "its etymology",
           "the practical effects we conceive the object of the conception to have",
           "the Church’s definition",
           "whatever we like",
           "b",
           "LookFor: effects, not ‘cash value’ as a later slogan only. Hardness as a conception of would-be interactions is the famous example."),
        tf(3, "Peirce thinks a perfectly clear idea can still be empty of conceivable practical bearings.",
           "false",
           "Clarity in the third grade is those bearings. That is the paper’s point against Cartesian ‘clarity.’"),
    )
    add(
        "james-pragmatism",
        "After Pragmatism (assigned lectures)",
        "Truth in the making, without ‘whatever I wish.’",
        mc(1, "James’s pragmatism treats a true idea as",
           "a copy of a static reality with no further office",
           "one that we can assimilate, validate, corroborate, and verify — truth happens to an idea",
           "whatever is expedient in the way of our private cheating",
           "a Kantian thing in itself",
           "b",
           "LookFor: the cash-value lecture’s care. ‘Expedient’ is fenced by the long run and the face of other truths."),
        mc(2, "A common misreading to refuse is that James",
           "cares about verification",
           "means that a comforting falsehood is true if it pleases me this afternoon",
           "talks of leading and working",
           "inherits Peirce’s maxim with a difference",
           "b",
           "The sitting asked you to state the view so it is not a joke. Other truths and the long run are the fence."),
        tf(3, "James presents pragmatism as a method of settling metaphysical disputes by tracing practical differences.",
           "true",
           "That is the method lecture. If two formulas make no difference in practice, the dispute is idle."),
    )
    add(
        "james-will-to-believe",
        "After ‘The Will to Believe’",
        "Forced, live, momentous options.",
        mc(1, "James’s thesis is that",
           "we should always wait for sufficient evidence in every domain, including the religious",
           "when an option is living, forced, and momentous, and intellect cannot decide, it can be lawful to will a belief that runs ahead of proof",
           "Pascal’s Wager is a demonstration",
           "all belief is immoral",
           "b",
           "The three marks of the genuine option are the lookFor. Without them the essay is misread as ‘believe whatever.’"),
        mc(2, "Clifford’s ethic (‘it is wrong always to believe on insufficient evidence’) is rejected when",
           "evidence is abundant",
           "waiting itself is a kind of bet — as in friendship or religion — so ‘neutrality’ is already a choice",
           "James denies all evidence",
           "only scientists exist",
           "b",
           "The sitting: not a license for wishful meteorology. The domain is restricted."),
        tf(3, "James argues that one ought to will beliefs about next week’s weather without data.",
           "false",
           "Weather is not a genuine option of the religious/moral type the essay isolates."),
    )
    add(
        "dewey-reconstruction",
        "After Reconstruction in Philosophy (assigned)",
        "Philosophy as a response to problems of life, not a museum.",
        mc(1, "Dewey’s reconstruction aims to",
           "restore medieval systems unchanged",
           "shift philosophy from allegedly ultimate being toward methods of inquiry that deal with present social and scientific problems",
           "deny all science",
           "return to the Cave’s prisoners as an ideal",
           "b",
           "LookFor: the change in philosophy’s office. Not a biography of Chicago."),
        mc(2, "A dualism Dewey wants undone is typically",
           "only grammar",
           "knowing vs doing, or a spectator theory of knowledge detached from practice",
           "the existence of schools",
           "all use of logic",
           "b",
           "Reconstruction is a program. The quiz checks the assigned diagnosis."),
        tf(3, "Dewey treats inherited philosophical problems as always merely verbal and never historically rooted in life.",
           "false",
           "He historicizes them as responses — then asks whether they still serve."),
    )
    add(
        "dubois-souls",
        "After The Souls of Black Folk (assigned chapters)",
        "Double-consciousness as a philosophical structure.",
        mc(1, "Double-consciousness names",
           "a medical diagnosis only",
           "the sense of always looking at oneself through the eyes of a white world — two-ness of American and Negro",
           "Hegel’s lordship without remainder",
           "Mill’s harm principle",
           "b",
           "The sitting: a structure of self-knowledge under domination, not a memoir-only reading."),
        mc(2, "The Veil in these pages is",
           "a fashion",
           "the barrier that splits worlds of meaning and recognition — Du Bois’s image for lived segregation of experience",
           "Kant’s noumena",
           "a social contract",
           "b",
           "LookFor: the image as analysis. The sorrow songs, if assigned, are evidence, not decoration."),
        tf(3, "Du Bois presents the problem of the color-line as merely a failure of individual manners, with no historical structure.",
           "false",
           "The opening of the book is a world-historical claim about the twentieth century’s problem."),
    )
    add(
        "moore-principia",
        "After Principia Ethica (assigned opening)",
        "The naturalistic fallacy, and good as simple.",
        mc(1, "Moore claims that ‘good’ is",
           "identical with pleasure",
           "a simple, unanalyzable non-natural property — defining it as some natural property is the naturalistic fallacy",
           "a Kantian form of law",
           "whatever the sovereign commands",
           "b",
           "LookFor: simple/indefinable, and the fallacy as Moore states it (not later textbook variants only)."),
        mc(2, "The open-question argument is meant to show that",
           "ethics is impossible",
           "for any proposed analysis ‘good = X,’ it remains an open question whether X is good — so the analysis fails",
           "only poets know good",
           "Mill already defined good",
           "b",
           "You may reject the argument. You must state it as a test of definitions."),
        tf(3, "Moore thinks ethics should begin by defining good as evolutionary fitness.",
           "false",
           "That would be a naturalistic identification of the kind he attacks."),
    )
    add(
        "russell-problems-appearance",
        "After Problems of Philosophy (appearance)",
        "The table, sense-data, and what we may still know.",
        mc(1, "Russell’s table example is meant to show that",
           "tables do not exist",
           "what is immediately known in seeing is not the public table as physics describes it, but sense-data",
           "Berkeley already ended philosophy",
           "matter is a Form",
           "b",
           "Appearance vs reality is the sitting’s tool. Idealism is a live option he will not simply swallow."),
        mc(2, "A sense-datum, here, is",
           "the physicist’s atom",
           "the color-patch, hardness, etc., immediately present in experience",
           "an innate idea",
           "the thing in itself as Kant’s noumenon",
           "b",
           "LookFor: the distinction. Knowledge by acquaintance vs description waits in nearby chapters if assigned."),
        tf(3, "Russell uses the table to prove that science is false.",
           "false",
           "He is locating what is certain in perception so that physical objects can be inferred — a problem, not a dismissal."),
    )
    add(
        "russell-problems-induction",
        "After Problems of Philosophy (induction)",
        "The principle we cannot prove and cannot do without.",
        mc(1, "The problem of induction, as Russell states it, is that",
           "we never observe anything twice",
           "the inference from ‘this has happened’ to ‘it will happen’ is not logically guaranteed, yet science and life require it",
           "Hume already solved it by custom, so there is no problem",
           "only miracles are inductive",
           "b",
           "The sitting continues Hume without stopping at therapy. Russell wants the principle named."),
        mc(2, "Russell’s attitude is roughly that",
           "we should stop expecting sunrise",
           "we must accept a principle of induction (or equivalent) as a postulate of knowledge, not a theorem from experience alone",
           "the copy principle proves the future",
           "Kant’s categories are unnecessary to mention",
           "b",
           "LookFor: postulate vs proof. A common error is to think he ‘refutes’ Hume by ignoring him."),
        tf(3, "This chapter claims induction is a demonstration like arithmetic.",
           "false",
           "If it were, it would not be the problem of philosophy it is."),
    )
    add(
        "tractatus-picture",
        "After Tractatus (assigned early propositions)",
        "The world as facts, and the picture.",
        mc(1, "‘The world is all that is the case’ introduces",
           "a heap of things without structure",
           "the world as the totality of facts, not of things — a logical space of states of affairs",
           "Hegel’s Absolute",
           "ordinary language as already perfect",
           "b",
           "LookFor: facts vs things. The picture theory is how a proposition can be true or false."),
        mc(2, "A proposition is a picture in that",
           "it is a painting in a gallery",
           "it shares logical form with a possible state of affairs — it shows how things stand if true",
           "it is a private mental image only",
           "it names a Form",
           "b",
           "The sitting: sense as possible situation, not as a psychological association."),
        tf(3, "The early Tractatus treats ethics and the mystical as additional facts in the world among others.",
           "false",
           "That is what the later assigned sitting on the unsayable will press. Early on, the picture is of sayable facts."),
    )
    add(
        "tractatus-silence",
        "After Tractatus (assigned later propositions)",
        "What cannot be said, and the ladder.",
        mc(1, "The propositions of the Tractatus, on its own close, are",
           "ordinary empirical reports",
           "elucidations to be thrown away — a ladder — once one has seen the world rightly",
           "a Hegelian system to keep",
           "rules of etiquette",
           "b",
           "6.54: throw away the ladder. The sitting is that paradox, not a biography."),
        mc(2, "What we cannot speak about",
           "should be written as more propositions of the same scientific type",
           "we must pass over in silence — ethics, the mystical, the limit of the world are not further facts",
           "does not exist in any sense Wittgenstein cares about",
           "is identical with Hume’s missing shade",
           "b",
           "LookFor: the limit of language as the ethical/mystical, not a gag order on poetry only."),
        tf(3, "The Tractatus ends by adding extra scientific facts about God as an object in the world.",
           "false",
           "God does not reveal himself in the world (6.432). Silence is the point."),
    )

    # Bibliographic: test ideas, no long quotation
    add(
        "wittgenstein-investigations",
        "After Philosophical Investigations §§1–43",
        "A check on the assigned move, not a biography.",
        mc(1, "The shopkeeper / five red apples example is meant to show that",
           "grocers are philosophers",
           "understanding a word is not always having a mental picture of an object — it can be mastery of a technique in a practice",
           "Augustine’s picture is already sufficient",
           "meaning is a private inner pointing that needs no public criteria",
           "b",
           "The sitting named this example. It cracks the ‘words as names of objects’ picture without requiring you to quote the book."),
        mc(2, "A language-game, as used in these sections, is",
           "a complete theory of all language",
           "a comparison: looking at primitive practices of using words, to loosen the grip of one picture",
           "a proof that anything I say is correct",
           "the Tractatus picture theory restated",
           "b",
           "LookFor: comparison, not a theory of everything. ‘Meaning as use’ is not ‘words mean whatever I like.’"),
        mc(3, "Family resemblance is offered as",
           "a biological taxonomy of concepts with necessary and sufficient conditions for ‘game’",
           "a warning against assuming one essence hidden behind all uses of a word",
           "a return to Platonic Forms",
           "a refutation of all philosophy",
           "b",
           "The assignment asked whether it is a theory of concepts or a warning. The latter is the safer reading of §§1–43."),
        tf(4, "These sections leave the Tractatus picture theory untouched as an account of ordinary talk.",
           "false",
           "Ostension and naming as the whole story is what is under attack — the Tractatus’s picture of sense does not survive unchanged."),
    )
    add(
        "heidegger-being-time",
        "After Being and Time, Introduction §§1–4",
        "The question of being, not a life of Heidegger.",
        mc(1, "‘Being is not a being’ in this introduction means that",
           "nothing exists",
           "the question of what it means to be is not answered by pointing to an entity among entities (God, nature, the subject)",
           "only science speaks",
           "Russell’s table is the first question",
           "b",
           "LookFor: being is not a being. That is the forgotten question."),
        mc(2, "Dasein is introduced as",
           "a Cartesian ego with properties first",
           "the entity that we are, whose being is an issue for it — the one that understands being",
           "a physical object in space as physics starts",
           "a synonym for ‘human nature’ as a biological essence",
           "b",
           "The Cartesian starting point is what is being refused: not a subject inspecting objects as the first move."),
        mc(3, "This introduction is best taken as",
           "the whole of Being and Time",
           "a new subject-matter and method: fundamental ontology via the being that asks",
           "a commentary on Mill",
           "a proof of God",
           "b",
           "The assignment: method and subject-matter, not the whole published book."),
        tf(4, "Heidegger’s opening treats ‘being’ as one more item in an inventory of beings, like a rare mineral.",
           "false",
           "That confusion is exactly the forgetfulness the introduction diagnoses."),
    )
    add(
        "sartre-existentialism",
        "After Existentialism Is a Humanism",
        "Existence precedes essence — as the lecture defines it.",
        mc(1, "‘Existence precedes essence’ denies that",
           "humans exist",
           "there is a maker’s blueprint or given human nature that would tell you in advance what you ought to be",
           "choices have consequences",
           "other people exist",
           "b",
           "LookFor: no prefabricated human essence. That is the hook of the lecture."),
        mc(2, "In choosing, on Sartre’s public account here, you",
           "choose only a private whim with no image of the human",
           "choose an image of the human that you take as valid for all — hence anguish",
           "follow a ready-made Kantian table of duties as the whole story",
           "escape responsibility by citing nature",
           "b",
           "Anguish, abandonment, despair are technical. Quietism is the charge he answers by calling this a humanism."),
        tf(3, "The lecture presents existentialism as an excuse to do nothing, because values are absurd.",
           "false",
           "He offers it as a humanism against quietism: one must still choose and invent."),
        mc(4, "A serious question the assignment left open is whether ‘choosing for all’",
           "is a recipe for a banquet",
           "smuggles a universalizing demand without Kant’s moral law as its ground",
           "is identical with Mill’s competent judges",
           "refutes Hobbes",
           "b",
           "That was one of the seminar questions. The quiz only needs you to recognize the tension."),
    )
    add(
        "quine-two-dogmas",
        "After ‘Two Dogmas of Empiricism’",
        "The two dogmas, and the web.",
        mc(1, "The two dogmas Quine names are",
           "God and the soul",
           "the analytic/synthetic distinction and reductionism (each statement to a sensory confirming/infirming range)",
           "innate ideas and Forms",
           "master and slave",
           "b",
           "LookFor: name the dogmas. Without that, holism has nothing to replace."),
        mc(2, "Synonymy does not easily save analyticity, on his argument, because",
           "dictionaries are illegal",
           "explanations of analyticity via synonymy, definition, or necessity tend to circle rather than ground the distinction",
           "no one uses language",
           "Kant already forbade the word",
           "b",
           "The essay’s first half is this circle. Do not skip it for the slogan ‘web of belief.’"),
        mc(3, "The web of belief says that",
           "each sentence faces experience alone",
           "statements meet the tribunal of experience as a corporate body — any statement can be held true if we make enough adjustments elsewhere",
           "science never revises",
           "only protocol sentences are revisable",
           "b",
           "Holism is a picture of science, not automatically a Pyrrhonian skepticism. That was a seminar question."),
        tf(4, "Quine thinks the analytic/synthetic cut is as sharp as Kant needed for the synthetic a priori.",
           "false",
           "If the cut goes, that Kantian architecture is among the casualties the assignment asked you to consider."),
    )
    add(
        "anscombe-modern-moral",
        "After ‘Modern Moral Philosophy’",
        "Ought without a lawgiver, and a pause.",
        mc(1, "Anscombe wants moral philosophy laid aside until we have",
           "more utilitarian calculations",
           "an adequate philosophy of psychology (intention, action, desire) — otherwise ‘ought’ is a surviving fragment",
           "a return to Hobbes only",
           "a proof that Aristotle is useless",
           "b",
           "LookFor: psychology first. That is the paper’s shock."),
        mc(2, "The diagnosis of modern ‘ought’ is that it",
           "is a new scientific discovery",
           "is a survivor of a divine-law conception of ethics, now without a lawgiver — hence incoherent as used",
           "is identical with Aristotle’s mean",
           "should be maximized as pleasure",
           "b",
           "She is asking a certain ethics class to stop. Both thin duty-talk and a certain consequentialism are in the dock."),
        tf(3, "The paper claims that Aristotle’s vocabulary of virtue is what we should simply resume without any philosophy of action.",
           "false",
           "Virtue ethics is in the offing, but her demand is a psychology of intention — not a slogan ‘be like Aristotle.’"),
        mc(4, "A fair reading of her target is",
           "only ancient ethics",
           "a modern moral philosophy that keeps a law-sense of ‘ought’ while dropping the theological framework that made that sense",
           "all uses of the word ‘good’",
           "Mill’s harm principle as a political rule only",
           "b",
           "The assignment: what she wants us to stop doing in ethics class. Name the diagnosis."),
    )
    add(
        "rawls-justice",
        "After A Theory of Justice (assigned sections)",
        "A device, two principles, not a history.",
        mc(1, "The original position is",
           "a historical assembly in 1776",
           "a point of view: parties behind a veil of ignorance choosing principles of justice for the basic structure",
           "Hobbes’s war",
           "a utilitarian sum of pleasures as the first principle",
           "b",
           "LookFor: a device, not a place. The veil screens off morally irrelevant bargaining advantages."),
        mc(2, "The two principles, in order, concern",
           "wealth first, then speech",
           "equal basic liberties; then social and economic inequalities arranged for the greatest benefit of the least advantaged, consistent with fair equality of opportunity",
           "the difference principle alone as a complete theory",
           "maximax for the most talented as the first rule",
           "b",
           "Priority of liberty, then the difference principle. Not simple equality, not maximax for the gifted."),
        mc(3, "The difference principle is not simple equality because",
           "Rawls hates the poor",
           "inequalities can be just if they raise the position of the worst off compared with a more equal scheme",
           "there is no veil",
           "it is Mill’s harm principle",
           "b",
           "LookFor: not equality, not maximax for the talented. That is the economic content after Kantian procedure."),
        tf(4, "Justice as fairness, in the assigned sections, is presented as a utilitarian average of happiness.",
           "false",
           "It is offered as a rival to utilitarianism: the parties would not choose to sacrifice the few as a mere sum."),
    )
    add(
        "foucault-discipline",
        "After the Panopticism chapter",
        "A diagram of power, not a biography.",
        mc(1, "The Panopticon, in this chapter, functions as",
           "only a failed building",
           "an architectural and social diagram: perpetual possible visibility that produces self-discipline",
           "Hobbes’s sword made of glass",
           "Rawls’s original position",
           "b",
           "LookFor: diagram. Bentham’s plan becomes a figure of modern power."),
        mc(2, "Power here is described as",
           "only the sovereign’s right to kill",
           "productive: it makes subjects, habits, and visibilities, not merely forbidding acts from outside",
           "identical with Mill’s harm principle",
           "absent from schools and barracks",
           "b",
           "The contrast with Hobbes’s visible sovereign was a lookFor. Discipline is capillary, not only spectacular."),
        tf(3, "The chapter treats modern punishment as merely the absence of the old scaffold, with no new positive techniques.",
           "false",
           "Discipline is a positive technology of bodies and souls — that is the genealogical sting."),
        mc(4, "A fair critical question the assignment allowed is whether this is",
           "a recipe for a panopticon in your house",
           "a reading of a prison plan that may be overextended into a total theory of modernity",
           "a proof of the Forms",
           "identical with Nietzsche’s Genealogy word for word",
           "b",
           "Seminar question: theory of modernity vs overextended prison plan. Recognize the stakes."),
    )
    add(
        "murdoch-sovereignty",
        "After ‘The Sovereignty of Good’",
        "Vision and attention, against a naked will.",
        mc(1, "Murdoch’s complaint about a certain modern moral agent is that",
           "people think too much about art",
           "the picture of a naked will issuing choices (existentialist/Kantian thinness) misses moral life as vision and attention",
           "Aristotle is the enemy",
           "only politics matters",
           "b",
           "LookFor: what is wrong with will as the whole of morals."),
        mc(2, "Attention (as in the mother-in-law example) is",
           "a distraction from duty",
           "moral activity: a just and loving gaze that can change what is there to be seen, without a new public act",
           "identical with Sartre’s anguish",
           "a utilitarian calculation",
           "b",
           "The example is the sitting’s tool. Unselfing is the work."),
        mc(3, "The Good, for her, functions as",
           "a product we choose like a brand",
           "a magnetic, transcendent orientation of the soul — Platonic without cheap mysticism",
           "the difference principle",
           "the death of God as Nietzsche’s madman",
           "b",
           "LookFor: magnetic, not chosen as a consumer. Compare the Cave without assuming identity."),
        tf(4, "Murdoch treats moral improvement as only a series of isolated choices with no change in vision.",
           "false",
           "The whole essay is against that picture. Vision comes first."),
    )
    add(
        "map-analytic",
        "After the analytic map",
        "Can you place three live problems without collapsing them into this course’s earlier slogans?",
        mc(1, "A language problem that is not merely ‘picture vs use’ restated would be, for example,",
           "whether names refer by description or by a causal-historical chain (the cluster around Kripke’s lectures)",
           "whether Plato wrote the Apology",
           "whether Epicurus liked bread",
           "whether the Cave has four segments",
           "a",
           "The assignment asked for one language problem that is not the Tractatus/Investigations contrast again. Reference and necessity is the standard next door."),
        mc(2, "Gettier-style cases are for",
           "proving that no one knows anything",
           "showing that justified true belief, as a simple analysis, is not sufficient for knowledge",
           "replacing ethics",
           "refuting Du Bois",
           "b",
           "LookFor: justification vs knowledge. That is the map pin, not a biography of Gettier."),
        mc(3, "A mind problem that is not only ‘Descartes was a dualist’ would ask, for example,",
           "whether mental states are identical with brain states, functional roles, or irreducible experiences",
           "whether Hobbes liked geometry",
           "whether the wax melts",
           "whether Locke listed qualities",
           "a",
           "Identity theory, functionalism, consciousness: the living cluster after dualism as a museum piece."),
        tf(4, "This sitting required you to paste a copyrighted handbook chapter into the app.",
           "false",
           "The assignment forbade that. The quiz is whether you can name legal next texts and locate problems."),
    )
    add(
        "map-continental-ethics",
        "After the second map",
        "Continuations: phenomenology, power, and ancient ethics still speaking.",
        mc(1, "A phenomenological problem that is not ‘Heidegger said being’ might be",
           "how the lived body is our hold on the world (after Merleau-Ponty), or how the face of the other obligates (Levinas)",
           "whether Thales said water",
           "whether the Five Ways number five",
           "whether Hume defined a miracle",
           "a",
           "The assignment asked for a problem, not a name-drop. Body and other are standard next sittings."),
        mc(2, "A political problem after Rawls and Foucault could be",
           "whether the table is brown",
           "recognition, domination, gender, or race as structures that a veil of ignorance or a panoptic diagram might miss or reveal",
           "whether monads have windows",
           "whether the slave-boy recollects geometry",
           "b",
           "LookFor: one political problem after those two. Feminist philosophy and philosophy of race after Du Bois were named."),
        mc(3, "Ancient ethics (Aristotle, Stoics) still speaks in applied ethics when, for example,",
           "one asks about character, habituation, or what is up to us in medicine and technology, not only about a single maximizing rule",
           "one discards all later philosophy",
           "one treats eudaimonia as GDP",
           "one quotes Burnet on water as a clinical guideline",
           "a",
           "The map asked how this course’s ancient ethics might still speak. Virtue and assent are the bridge, not a slogan."),
        tf(4, "Finishing this course means there is no next sitting to choose.",
           "false",
           "The last nextHint: there is a next reading you can now choose with judgment."),
    )

    return q
