"""Quizzes: Hellenistic through Leibniz."""
from course_helpers import mc, tf, ms, make_quiz


def all_quizzes():
    q = {}

    def add(aid, title, intro, *questions):
        q[aid] = make_quiz(aid, title, intro, list(questions))

    add(
        "epicurus-menoeceus",
        "After the Letter to Menoeceus",
        "Pleasure as a disciplined end, not a banquet.",
        mc(1, "Epicurus classifies desires so that ataraxia is possible. Empty desires are those that",
           "are natural and necessary, like hunger",
           "have no natural limit and are produced by false beliefs about what we need",
           "are identical with prudence",
           "only the gods have",
           "b",
           "Natural/necessary vs empty is the letter’s practical physics of the soul. Unlimited wants cannot be satisfied, so they cannot be the end."),
        mc(2, "‘Death is nothing to us’ depends on the claim that",
           "the soul survives and is rewarded",
           "when we exist, death is not present, and when death is present, we do not",
           "death is painful but brief",
           "the unborn suffer the way the dead do",
           "b",
           "No subject remains to be harmed. That is why the letter can treat death-fear as a confusion, not a fate."),
        mc(3, "Prudence is called more precious than philosophy because",
           "Epicurus hates inquiry",
           "it is the practical wisdom that chooses among pleasures and produces a stable life",
           "it is identical with luxury",
           "Aristotle already proved this",
           "b",
           "The letter’s hedonism is a discipline: the many’s frenzy is exactly what prudence refuses."),
        tf(4, "On this letter, every pleasure is to be pursued as it arises.",
           "false",
           "Some pleasures bring greater pains. The classification of desires is the filter."),
    )
    add(
        "lucretius-atoms",
        "After Lucretius I",
        "Physics as a therapy of fear.",
        mc(1, "Lucretius argues that something cannot arise from nothing because otherwise",
           "the gods would be unemployed",
           "anything could come from anything, and there would be no need of seed or season",
           "void would be impossible",
           "Aristotle’s four causes would be confirmed",
           "b",
           "The ‘nothing from nothing’ rule is a constraint on explanation: generation needs a determinate source."),
        mc(2, "Void is required, as in the older atomists, because",
           "void is a god",
           "body cannot move or yield if there is no empty interval",
           "Parmenides proved void exists",
           "void is the same as the soul",
           "b",
           "Motion needs somewhere to go. Book I puts Eleatic pressure to work for Epicurean physics."),
        mc(3, "In this book, the physics is already ethics because",
           "Lucretius forbids all pleasure",
           "if thunder and plague are atomic, they need not be read as divine punishment",
           "only priests may study atoms",
           "void is a moral law",
           "b",
           "The sitting: a therapy of fear. Superstition is a mistaken physics."),
    )
    add(
        "lucretius-death",
        "After Lucretius III",
        "No surviving subject, no posthumous harm.",
        mc(1, "The soul must be bodily, on Lucretius’s opening moves, because",
           "Plato said so",
           "it affects and is affected with the body — it moves a body and suffers with it",
           "only gods have souls",
           "void thinks",
           "b",
           "An incorporeal soul could not shove atoms. Mortality of mind follows from its atomic structure."),
        mc(2, "Death cannot harm the one who dies, in the central argument, because",
           "death is pleasant",
           "the compound dissolves, so there is no remaining subject of experience",
           "the unborn are happier than we are",
           "the gods forgive everyone",
           "b",
           "The assignment distinguished this from a proof that death is not bad in every sense — it shows the impossibility of post-mortem experience."),
        mc(3, "The time before birth is invoked as",
           "proof of reincarnation",
           "an analogue: we do not lament the ages before we existed, so why lament the ages after?",
           "Aristotle’s function argument",
           "a proof that the soul is immortal",
           "b",
           "Symmetry with the unborn is the consolation-image. A dualist must deny the soul’s dissolution."),
        tf(4, "Book III claims that death is bad because it deprives us of future pleasures we would have enjoyed.",
           "false",
           "That deprivation view is exactly what the no-subject argument is meant to undercut — or at least to recast."),
    )
    add(
        "epictetus-enchiridion-i",
        "After Enchiridion (opening)",
        "What is up to us.",
        mc(1, "The handbook’s first cut is between",
           "Greeks and Romans",
           "what is up to us (judgment, impulse, desire) and what is not (body, property, reputation, office)",
           "pleasure and pain as Epicurus ranked them",
           "Forms and particulars",
           "b",
           "Freedom is relocated inside assent. Confusing the two classes is the source of disturbance."),
        mc(2, "If something is not up to you, the disciplined response is",
           "to pretend it is, so you stay ambitious",
           "not to treat it as good or evil in the strict sense — not to stake your eudaimonia on it",
           "to ignore all politics forever",
           "to seek more of it",
           "b",
           "The sitting is not quietism as a mood. It is a classification of value."),
        tf(3, "Epictetus teaches that you can, with enough effort, make other people’s opinions up to you.",
           "false",
           "Reputation is listed among things not up to us. The work is on the use of impressions."),
    )
    add(
        "epictetus-enchiridion-ii",
        "After Enchiridion (use)",
        "Impressions, roles, and the inner citadel in practice.",
        mc(1, "When a troubling impression appears, the handbook’s move is to",
           "immediately assent that the world is bad",
           "pause and test: is this something up to me, and what has been added by my judgment?",
           "consult an oracle",
           "change the cosmos first",
           "b",
           "Assent is the free act. The world does not have to change for the passion to lose its necessity."),
        mc(2, "Playing a role (child, citizen, guest) in these later chapters means",
           "hypocrisy",
           "performing the duties of the part assigned, without demanding that the script be rewritten",
           "abandoning all ethics",
           "becoming a professional actor",
           "b",
           "The sitting asked you not to romanticize: duty in a role is not a feeling of serenity."),
        mc(3, "A plausible misreading to refuse is that Stoicism here is",
           "a discipline of judgment",
           "a promise that nothing painful will happen to the body",
           "an account of what is up to us",
           "a handbook for use, not a metaphysics textbook",
           "b",
           "Body and death remain not up to you. The good is not the body’s immunity."),
    )
    add(
        "marcus-meditations",
        "After Marcus (selected books)",
        "A notebook, not a system — but the same cut.",
        mc(1, "Marcus repeatedly returns to the thought that",
           "he can control the empire’s outcomes",
           "other people’s wrongdoing and cosmic events lie outside his ruling faculty, which he can keep just",
           "pleasure is the highest good",
           "the Forms will save Rome",
           "b",
           "The Meditations apply Epictetus’s cut in an emperor’s isolation. Do not turn them into a brand."),
        mc(2, "When Marcus writes of nature or the Whole, he is typically",
           "denying physics",
           "locating himself as a part among parts — so that anger at the universe is a confusion of scale",
           "quoting Lucretius with approval of atoms only",
           "founding a church",
           "b",
           "Cosmopolitan belonging is the metaphysical background of the notebook’s ethics."),
        tf(3, "The Meditations are best read as proofs intended to convince a hostile jury.",
           "false",
           "They are spiritual exercises. The quiz checks whether you found the repeated moves, not a treatise’s lemmas."),
    )
    add(
        "sextus-outlines-i",
        "After Outlines of Pyrrhonism I",
        "Suspension, not a secret dogma.",
        mc(1, "The Pyrrhonist’s advertised goal in Book I is",
           "to prove that nothing exists",
           "ataraxia following epochē — suspension of judgment on non-evident matters",
           "to become a Stoic sage",
           "to found a physics of atoms",
           "b",
           "Quiet comes after suspension, not after a rival metaphysics. That is the school’s claim."),
        mc(2, "The modes (tropes) function as",
           "demonstrations that the skeptic has a hidden doctrine of truth",
           "ways of opposing appearances to appearances so that assent is withheld",
           "Aristotle’s four causes",
           "proofs of the Forms",
           "b",
           "Equipollence: equally strong on both sides. The skeptic lives by appearance without claiming a criterion of the non-evident."),
        mc(3, "A serious question the sitting left you with is whether the skeptic",
           "never eats",
           "can live by appearances while claiming to suspend on all belief — or smuggles beliefs in",
           "is identical with Descartes",
           "denies that honey tastes sweet",
           "b",
           "The ‘apraxia’ charge is the old objection. Sextus’s answer is life by the apparent, not dogma."),
        tf(4, "Sextus’s Book I is mainly a biography of Pyrrho’s travels.",
           "false",
           "It is a method: tropes, criterion, and the promise of quiet."),
    )
    add(
        "plotinus-hypostases",
        "After Plotinus (selected Enneads)",
        "The One, Intellect, Soul — not a fourth god.",
        mc(1, "In the Plotinian cascade, the One is",
           "a being among beings, with parts",
           "beyond being and intellect, the source from which Intellect and Soul proceed without emptying it",
           "identical with matter",
           "the Roman emperor",
           "b",
           "The sitting: hypostases as a metaphysics of procession, not a committee of deities."),
        mc(2, "Soul’s philosophical problem here is",
           "how to win elections",
           "how a unity can be the life of a many — turning toward Intellect vs dispersing into bodies",
           "how to deny the One",
           "how to become an atom",
           "b",
           "Ascent is conversion of attention, continuous with Plato’s Cave but now as a cosmology."),
        tf(3, "Matter, on this picture, is a positive evil substance equal to the One.",
           "false",
           "Typical Plotinian line: matter as privation or last outflow, not a rival first principle. (Keep to the selected pages’ emphasis on hypostases.)"),
    )
    add(
        "boethius-consolation",
        "After Consolation (I and III)",
        "Fortune’s wheel, and where the good actually sits.",
        mc(1, "Lady Philosophy’s opening work in Book I is to",
           "restore Boethius’s political office",
           "diagnose his exile as a confusion about what is truly his, and about Fortune",
           "prove the Forms in Aristotle’s sense",
           "convert him to Epicurus",
           "b",
           "The prison is the occasion; the disease is mislocated good."),
        mc(2, "Book III’s argument about happiness is that",
           "wealth, office, and fame are complete goods",
           "partial goods (wealth, honor, power, pleasure) cannot be the true good because they fail of self-sufficiency and unity",
           "there is no God",
           "Fortune is the highest good",
           "b",
           "The sitting: a Platonic-Aristotelian inventory of false goods, then the turn to the highest good."),
        mc(3, "A reader who stops at ‘everything happens for the best’ has",
           "finished Philosophy’s argument",
           "missed the work of distinguishing providence, fate, and the location of beatitude — slogans are not the consolation",
           "refuted Boethius",
           "quoted Book I only",
           "b",
           "The assignment is the argument, not a proverb."),
    )
    add(
        "augustine-confessions-evil",
        "After Confessions VII",
        "Evil as privation, not a rival substance.",
        mc(1, "In Book VII, a central metaphysical claim about evil is that",
           "evil is a positive substance equal to God",
           "evil is a privation of good in a will or nature that remains, as being, from God",
           "matter is created by an evil demiurge",
           "God authors sin as a thing",
           "b",
           "Manichaean dualism is the foil. If God is the source of all that is, evil cannot be a co-eternal stuff."),
        mc(2, "Augustine’s intellectual conversion in this book includes",
           "rejecting all Greek philosophy",
           "help from ‘Platonist’ books toward an incorporeal God and a non-Manichaean account of evil — still short of the will’s healing",
           "becoming a bishop in the same chapter",
           "proving the Five Ways",
           "b",
           "The sitting: metaphysics first; Book VIII is the will. Do not collapse them."),
        tf(3, "Book VII already narrates the garden scene of conversion of will.",
           "false",
           "That is Book VIII. VII is the intellectual problem of God and evil."),
    )
    add(
        "augustine-confessions-will",
        "After Confessions VIII",
        "Two wills, and a will that cannot will itself whole.",
        mc(1, "The ‘two wills’ analysis describes",
           "two gods",
           "a divided will that both wants and does not want the same conversion — not a second nature as the Manichees claimed",
           "Aristotle’s mean",
           "Stoic assent only",
           "b",
           "The sitting: inner conflict without dualist metaphysics. Habit and consent are the drama."),
        mc(2, "The garden scene is philosophically important because",
           "it is only autobiography with no argument",
           "the will’s turning is narrated as something that cannot be produced by more information alone — grace and example (the child’s song, the friends) enter the story",
           "Augustine proves God from motion",
           "it repeats Book VII’s Platonism word for word",
           "b",
           "You were asked to watch a will, not a theorem. Still: it is a philosophical claim about what knowledge cannot do."),
        mc(3, "A plausible misreading is that Augustine simply",
           "analyzes akrasia",
           "chooses Christianity because it is more useful for a career",
           "shows habit’s grip",
           "distinguishes knowing the good from doing it",
           "b",
           "The book is not career advice. It is the failure of a divided will to close itself."),
    )
    add(
        "augustine-confessions-time",
        "After Confessions XI",
        "Time as distension of the soul.",
        mc(1, "Augustine’s puzzle is that",
           "time is easy to define",
           "we speak of past and future, yet the past is no longer and the future is not yet — so where is time?",
           "only God has a clock",
           "Aristotle already ended the question",
           "b",
           "The famous ‘if no one asks me, I know’ opening is this puzzle."),
        mc(2, "His constructive suggestion is that time is",
           "a container God sits in",
           "a distension of the soul: memory, attention, expectation holding past, present, and future",
           "identical with the motion of the heavens only, with no soul",
           "unreal in every sense, so prayer is pointless",
           "b",
           "The sitting: not a physics paper. It is how a creature measures and lives time before an eternal God."),
        tf(3, "On this account, God is in time the way we are, only longer.",
           "false",
           "The contrast with divine eternity is the point of measuring our distension against what does not pass."),
    )
    add(
        "anselm-proslogion",
        "After the Proslogion’s argument",
        "That than which nothing greater can be thought.",
        mc(1, "Anselm’s formula for God in the argument is",
           "the most powerful being in the universe as a fact of astronomy",
           "that than which nothing greater can be thought",
           "the unmoved mover as in Physics",
           "whatever the fool says in his heart",
           "b",
           "The sitting is the formula and what it is supposed to do — not a later textbook label alone."),
        mc(2, "The argument’s controversial step is that",
           "existence in reality is greater than existence in the understanding alone, so the greatest conceivable cannot be only in the understanding",
           "the Bible already contains a proof",
           "Gaunilo is the fool",
           "faith is unnecessary",
           "a",
           "Even if you reject the step, you must state it. ‘Faith seeking understanding’ is the frame, not a skip."),
        tf(3, "Anselm presents the argument as a replacement for faith.",
           "false",
           "The Proslogion is fides quaerens intellectum: understanding sought from within faith, not a cold start from nowhere."),
    )
    add(
        "gaunilo-and-reply",
        "After Gaunilo and the reply",
        "Lost islands, and whether the formula is special.",
        mc(1, "Gaunilo’s ‘lost island’ is meant to show that",
           "islands cannot exist",
           "if Anselm’s form of argument worked, we could prove a greatest conceivable island exists — which we should not grant",
           "Anselm denied creation",
           "only monks may argue",
           "b",
           "The parody tests whether the formula applies uniquely to God or licenses any ‘greatest F’."),
        mc(2, "Anselm’s reply, in spirit, is that",
           "islands are nicer than God",
           "‘that than which nothing greater can be thought’ is not a contingent greatest-of-a-kind the way an island is — the fool already has God in intellect in a different way",
           "Gaunilo did not exist",
           "existence is never a perfection",
           "b",
           "You may still side with Gaunilo. The sitting is whether the formula is unique, not whether you like islands."),
        mc(3, "A good student mistake is to think Gaunilo",
           "denies that we can think of a lost island",
           "simply hasn’t read the Proslogion’s words, rather than offering a structural objection",
           "uses a parody of the form",
           "worries about illicit existence-inferences",
           "b",
           "He has read them. The objection is that the form proves too much."),
    )
    add(
        "averroes-decisive",
        "After the Decisive Treatise",
        "Law and demonstration as two addresses, not two truths as a slogan.",
        mc(1, "Averroes’s practical claim about philosophy and the Law is that",
           "philosophy is forbidden to all Muslims",
           "demonstration is a religious duty for those capable of it, and the Law has a rhetorical/poetic address for others",
           "the Quran has no inner sense",
           "Aristotle is a prophet in the legal sense",
           "b",
           "The sitting: who may allegorize, and why apparent conflict is not a license for the untrained to discard the Law."),
        mc(2, "When demonstration and the apparent sense of scripture seem to clash, Averroes’s trained reader",
           "throws out demonstration",
           "interprets the apparent sense, because truth does not contradict truth",
           "must become a skeptic",
           "must leave the community",
           "b",
           "That is the harmony thesis in this treatise — not a cheap ‘double truth’ meme unless you find it in the pages."),
        tf(3, "The Decisive Treatise argues that every believer must study the Physics.",
           "false",
           "The point is differential address: demonstration is not for every audience."),
    )
    add(
        "maimonides-guide",
        "After Guide I.50–52 (and the assigned stretch)",
        "Attributes, and what we may not say of God.",
        mc(1, "In this stretch, Maimonides is especially concerned to",
           "list God’s body-parts",
           "block univocal positive attributes that would make God composite or like creatures",
           "prove the Five Ways in Aquinas’s later numbering",
           "deny creation",
           "b",
           "The sitting: negative theology as a philosophical-religious discipline, not a vibe."),
        mc(2, "Equivocation on names of God matters because",
           "Hebrew has no grammar",
           "if ‘knows’ or ‘lives’ meant the same in God and in us, we would have imported creaturely structure into the divine",
           "only Greeks may name God",
           "attributes are identical with atoms",
           "b",
           "Look for the argument about attribution, not a biography of Maimonides."),
        tf(3, "These chapters teach that ordinary praise of God is always philosophically sufficient as it stands.",
           "false",
           "The Guide’s pressure is that unexamined speech is a theological error."),
    )
    add(
        "aquinas-sacred-doctrine",
        "After ST I q.1",
        "Why a ‘science’ of revelation.",
        mc(1, "Sacred doctrine is called a science, in q.1, because",
           "it uses no premises from revelation",
           "it proceeds from principles known by the light of a higher science (God’s knowledge / revelation), as subaltern sciences do",
           "it replaces all philosophy",
           "it is only poetry",
           "b",
           "The sitting: how theology can be a scientia without being a first philosophy that proves its own highest principles."),
        mc(2, "Philosophy is not useless here because",
           "Aquinas rejects Aristotle",
           "natural reason can demonstrate some preambles and can serve sacred doctrine without replacing it",
           "only the Five Ways count as philosophy",
           "faith is identical with geometry",
           "b",
           "q.1 sets the relation of the two lights before q.2’s ways."),
        tf(3, "Question 1 claims that sacred doctrine is unnecessary if one has the Physics.",
           "false",
           "Revelation is needed for an end that exceeds natural reason — that is the opening argument."),
    )
    add(
        "aquinas-five-ways",
        "After ST I q.2",
        "Five ways, not one slogan.",
        mc(1, "Each ‘way’ is, structurally,",
           "a proof from scripture quotation alone",
           "a movement from observed features of the world (motion, causation, contingency, degrees, governance) to a first that all call God",
           "Anselm’s formula restated five times",
           "a disproof of Aristotle",
           "b",
           "You were asked to state at least one way with its middle term, not to chant ‘first cause.’"),
        mc(2, "The ways, as Aquinas frames them, conclude to",
           "the Trinity in full",
           "a first source to which the name God is given — not yet the whole of Christian doctrine",
           "the non-existence of motion",
           "the Proslogion’s fool",
           "b",
           "A common misreading inflates q.2 into the Summa. It is a metaphysical approach to ‘whether God exists.’"),
        mc(3, "A student who says ‘science refuted the first way’ without stating the first way has",
           "completed the assignment",
           "skipped the sitting: you must first hear motion as reduction from potency, and a first mover as Aquinas argues it",
           "quoted q.1",
           "refuted Gaunilo",
           "b",
           "LookFor was the argument’s steps, not a newspaper headline."),
        tf(4, "The Five Ways are five versions of Anselm’s ontological argument.",
           "false",
           "They start from the world (a posteriori), not from the concept of that-than-which."),
    )
    add(
        "aquinas-natural-law",
        "After ST I–II qq.90 and 94",
        "Law’s definition, and the precepts of practical reason.",
        mc(1, "Law, in q.90, is",
           "whatever a tyrant utters",
           "an ordinance of reason for the common good, made by one who has care of the community, and promulgated",
           "identical with physical necessity",
           "only the Decalogue",
           "b",
           "Four notes. Missing any one (especially reason and common good) is a misreading of ‘law’ here."),
        mc(2, "The first precept of natural law in q.94 is",
           "maximize GDP",
           "good is to be done and pursued, and evil avoided — with natural inclinations specifying goods (life, knowledge, social life, etc.)",
           "there is no natural law, only command",
           "only monks have natural law",
           "b",
           "The sitting: synderesis / first practical principles, not a complete modern rights list."),
        mc(3, "Natural law can fail to be known in particular cases, on this account, because",
           "there is no such law",
           "passion, vice, and custom can obscure conclusions even if the first precept is not abolished",
           "only the sovereign creates all morality",
           "Aristotle denied practical reason",
           "b",
           "q.94’s discussion of change and ignorance is part of the doctrine, not a later footnote."),
    )
    add(
        "bacon-idols",
        "After Novum Organum I (idols)",
        "Four idols, as a discipline of the mind.",
        mc(1, "Bacon’s idols are",
           "Greek statues",
           "systematic prejudices of the tribe, cave, marketplace, and theatre that block a new induction",
           "Aristotle’s categories",
           "the four causes under new names",
           "b",
           "The sitting: diagnosis before method. Idols of the theatre include received philosophical systems."),
        mc(2, "Idols of the marketplace especially concern",
           "commerce only",
           "the deceit of words — names that muddle inquiry",
           "each person’s private den",
           "the human species’ senses as such",
           "b",
           "Tribe (human nature), cave (individual), marketplace (language), theatre (doctrine) — keep them distinct."),
        tf(3, "Bacon’s aim in this stretch is to defend scholastic disputation as the organon of the sciences.",
           "false",
           "Novum Organum is a replacement organon. The idols explain why the old one fails."),
    )
    add(
        "descartes-discourse",
        "After Discourse on the Method (assigned parts)",
        "Method, morale, and a first sketch of the ‘I’.",
        mc(1, "The method’s rules (Part 2) emphasize",
           "trusting custom in all things",
           "evidence, division of difficulties, order, and complete enumerations",
           "Aristotle’s Topics as sufficient",
           "never doubting the senses",
           "b",
           "The sitting is the rules as a discipline, not a biography of the stove."),
        mc(2, "The provisional morale (Part 3) is there because",
           "Descartes has already rebuilt all science",
           "one must live while the house of belief is under renovation — a temporary ethics of moderation and resolution",
           "the Church forbade all ethics",
           "it replaces the Meditations",
           "b",
           "Do not confuse the morale with the later metaphysics. It is a scaffold."),
        mc(3, "Part 4’s ‘I think’ sketch is",
           "a full physics of the heart",
           "a first publication of the cogito and a proof of God and the soul’s distinction — tighter in the Meditations",
           "a denial that God exists",
           "Locke’s blank slate",
           "b",
           "The Discourse is a public narrative; the Meditations will slow the same moves down."),
    )
    add(
        "descartes-meditations-1-2",
        "After Meditations I–II",
        "Doubt as an instrument, and the cogito.",
        mc(1, "The dreaming and deceiver hypotheses are meant to",
           "prove that Descartes never slept",
           "withdraw assent from all that can be doubted, including the senses and even mathematical belief under a powerful deceiver",
           "establish empiricism",
           "refute the cogito in advance",
           "b",
           "Methodic doubt is not a lifestyle. It is a filter for what is certain."),
        mc(2, "‘I am, I exist’ survives because",
           "the body is known first",
           "even if I am deceived, I who am deceived must be — thought is the attribute I cannot separate from myself here",
           "Aristotle defined the soul as this",
           "other minds assure me",
           "b",
           "The sitting: what I am, at this stage, is a thinking thing — not yet a proof of the body’s existence."),
        mc(3, "The wax example shows that",
           "wax is a Form",
           "the nature of the wax is grasped by the mind, not by the changing sensory appearances",
           "senses never err",
           "God is wax",
           "b",
           "It is an argument about intellect’s grasp of body, still inside Meditation II’s thin ontology."),
        tf(4, "By the end of Meditation II, Descartes has proved that other human bodies exist.",
           "false",
           "The external world waits. II secures the ‘I’ and a first account of mind."),
    )
    add(
        "descartes-meditations-3-4",
        "After Meditations III–IV",
        "God as guarantor, and the source of error.",
        mc(1, "The idea of God in III is used to argue that",
           "ideas have no cause",
           "a finite substance could not be the total cause of the idea of an infinite perfect being — so God exists as cause",
           "the evil genius has already won",
           "only the ontological argument counts",
           "b",
           "Causal adequacy of ideas is the engine. You may reject it; you must state it."),
        mc(2, "Meditation IV locates error in",
           "God’s will to deceive",
           "the will’s outrunning the intellect — judging beyond what is clearly and distinctly perceived",
           "the body’s atoms",
           "language as such",
           "b",
           "Theodicy of error: God is not a deceiver; misuse of freedom explains falsity."),
        tf(3, "A clear and distinct perception, for Descartes here, may still be false if God is no deceiver.",
           "false",
           "The divine guarantee is what makes C&D the rule of truth — that is the circularity worry you were asked to feel."),
    )
    add(
        "descartes-meditations-5-6",
        "After Meditations V–VI",
        "Essence of matter, God again, and the union.",
        mc(1, "Meditation V’s ontological argument claims that",
           "existence is never contained in an essence",
           "existence belongs to God’s essence as a mountain’s valley belongs to the mountain — God cannot be thought as not existing",
           "only physics proves God",
           "Anselm is rejected",
           "b",
           "A second theistic proof, from essence. Compare with III without collapsing them."),
        mc(2, "Meditation VI argues that",
           "the mind is a mode of body",
           "body exists, mind and body are really distinct, yet I am a union — sensation teaches the composite",
           "dreams are the only reality",
           "other minds are known by the cogito alone",
           "b",
           "The sitting: dualism plus embodied life. Neither slogan (‘only mind’ / ‘only machine’) is the whole of VI."),
        mc(3, "The real distinction of mind and body is argued from",
           "church authority only",
           "clearly conceiving one without the other, given God’s power to bring about what is clearly conceived",
           "the wax alone",
           "Hobbes’s politics",
           "b",
           "That is the modal argument for dualism. Keep it distinct from the union’s phenomenology."),
    )
    add(
        "spinoza-ethics-god",
        "After Ethics Part I",
        "God or Nature, and the affect of necessity.",
        mc(1, "For Spinoza in Part I, substance is",
           "created by a person-like God from nothing each day",
           "that which is in itself and conceived through itself — and there is only one, God or Nature, with infinite attributes",
           "a heap of atoms",
           "the human mind",
           "b",
           "Deus sive Natura. Finite things are modes, not rival substances."),
        mc(2, "Nothing is contingent, on this account, because",
           "Spinoza denies all explanation",
           "everything follows from the necessity of the divine nature; ‘could have been otherwise’ is a defect of our imagination",
           "only humans are free in Descartes’ sense",
           "Aristotle’s chance is the highest cause",
           "b",
           "The sitting: necessity as metaphysics, not a mood of fatalism as popularly pictured."),
        tf(3, "Part I treats God as a lawgiver who might have made a different world by arbitrary will.",
           "false",
           "Will and intellect in God are not a king’s choices. That is the anti-creation-as-decree move."),
    )
    add(
        "pascal-pensees",
        "After the Wager (and assigned Pensées)",
        "Reason’s limits, and a practical argument.",
        mc(1, "The Wager argues that",
           "God’s existence is demonstrated like a triangle",
           "if you must wager, the expected value of living as if God exists dominates, given infinite gain",
           "all religion is false",
           "the cogito proves faith",
           "b",
           "It is a practical argument under uncertainty, not a fifth Way."),
        mc(2, "A limit Pascal insists on is that",
           "geometry can prove the God of Abraham",
           "the heart has reasons, and the philosophical God is not yet the God of the patriarchs — the Wager sits inside that humility",
           "skepticism is impossible",
           "Jesuits are the only audience",
           "b",
           "The sitting: do not inflate the Wager into the whole of the Pensées, but do hear why it is not a theorem."),
        tf(3, "Pascal thinks the Wager replaces the need to live a religious life after deciding.",
           "false",
           "Custom, mass, and habituation are part of how one comes to believe — the fragment’s own continuation."),
    )
    add(
        "leibniz-monadology",
        "After the Monadology",
        "Windowless simples, and a pre-established harmony.",
        mc(1, "A monad is",
           "a tiny extended atom",
           "a simple, windowless substance whose inner states unfold from its complete concept — perception and appetition, not parts",
           "a mode of Spinoza’s one substance only, with no plurality of substances",
           "a Lockean blank paper",
           "b",
           "Simples without windows: no causal influx of accidents from outside."),
        mc(2, "Pre-established harmony is Leibniz’s way of saying that",
           "bodies push monads",
           "mind and body (and monads generally) agree because God created a world of substances whose programs correspond — not because they transduce force into thought",
           "Spinoza already said this",
           "there is only one monad",
           "b",
           "The sitting: a reply to Descartes’ union problem and to occasionalism, in a sentence."),
        mc(3, "This is ‘the best of possible worlds’ because",
           "there is no evil",
           "God chooses the world with the greatest variety/order among possibles — evil is permitted under that optimization, not as a first good",
           "Leibniz denies possibility",
           "monads can see out their windows after all",
           "b",
           "A theodicy, not a cheer. Voltaire’s later joke is not the text."),
        tf(4, "Monads have physical windows through which accidents migrate.",
           "false",
           "‘Windowless’ is the technical refusal of influx."),
    )

    return q
