"""Unit recap quizzes for units with 3+ assignments."""
from course_helpers import mc, tf, ms, make_recap


def all_recaps():
    r = {}

    def add(uid, title, intro, *questions):
        r[uid] = make_recap(uid, title, intro, list(questions))

    add(
        "socratic-method",
        "Socrates: recap",
        "Three sittings, one practice: definition, public examination, and the city’s claim on a life.",
        mc(1, "Across Euthyphro, Apology, and Crito, a Socratic question is typically a demand for",
           "a list of examples or a quotation from a poet as sufficient",
           "an account that can survive ‘why?’ — what piety, wisdom, or justice is",
           "a rhetorical victory in court",
           "a physics of atoms",
           "b",
           "Euthyphro makes the demand explicit; Apology and Crito spend that demand in a life."),
        mc(2, "The examined life in the Apology is",
           "a private hobby Socrates would drop to live",
           "a duty he will not trade for acquittal",
           "identical with Crito’s plan to escape",
           "a proof that he knows piety’s form",
           "b",
           "Crito then shows that the same man will not injure the laws to save that life."),
        mc(3, "The Laws’ speech in Crito is in tension with the Apology because",
           "both texts deny that Athens has laws",
           "he defies a jury’s verdict in one and refuses to destroy the legal order in the other",
           "Crito is not Socratic",
           "the oracle is repeated as a proof of piety",
           "b",
           "That tension is the unit’s point, not a continuity error."),
        tf(4, "By the end of this unit Socrates has stated the form of piety successfully.",
           "false",
           "Euthyphro ends in aporia. The unit teaches the method, not a completed definition."),
        mc(5, "A mistake this unit is designed to kill is that Socratic ignorance is",
           "a method and a moral stance",
           "a claim that nothing — including duty — can be known or cared about",
           "paired with examining others",
           "distinct from the old comic slander",
           "b",
           "He still claims things about death and justice. Ignorance is not nihilism."),
    )
    add(
        "justice-and-city",
        "Republic: recap",
        "From Thrasymachus’s challenge to a structure of soul and city, then to the Cave.",
        mc(1, "The constructive definition of justice in the city is",
           "the advantage of the stronger",
           "each part doing its own work — analogically in the soul",
           "returning weapons to madmen",
           "a complete legal code",
           "b",
           "Book I clears the site; Book IV builds. Do not stop at Thrasymachus."),
        mc(2, "Glaucon’s Gyges story forces Socrates to show that justice is",
           "only a social contract for the weak",
           "worth choosing even if one could be unjust without cost",
           "identical with Thrasymachus’s view",
           "unnecessary if one has a ring",
           "b",
           "That is why Book I’s demolitions were not yet enough."),
        mc(3, "Sun, line, and Cave together claim that",
           "education is filling a vessel",
           "the Good is a source of knowability and being, and education is a turning — with a political cost of return",
           "only images exist",
           "justice is the advantage of the tyrant",
           "b",
           "The Cave is knowledge and politics. The unit is not ‘Plato liked allegories.’"),
        tf(4, "The city–soul analogy is a finished proof that a person is just exactly when a city is.",
           "false",
           "It may illustrate a hypothesis. The unit asked you to keep that worry."),
        mc(5, "Book I’s remaining work, after the recap of the whole unit, is best described as",
           "the full theory of the philosopher-king",
           "putting the adult challenge (justice as another’s good, the happier unjust life) on the table",
           "the divided line",
           "Aristotle’s mean",
           "b",
           "Without Thrasymachus, Books IV and VII have no enemy."),
    )
    add(
        "aristotle-ethics-first-philosophy",
        "Aristotle: recap",
        "Happiness, virtue, wisdom, and what a science needs in order to start.",
        mc(1, "Eudaimonia in NE I is",
           "a passing mood",
           "activity of the soul in accordance with virtue over a complete life",
           "honor as the highest end",
           "the Form of the Good as Plato locates it",
           "b",
           "NE II then says what a virtue of character is. Keep the pair."),
        mc(2, "The mean is not mediocrity because",
           "it is a geometric midpoint the same for every body",
           "it is hitting the mark relative to us, as the phronimos would judge — courage is not half-cowardice",
           "virtue is a feeling",
           "knowledge without habituation is already virtue",
           "b",
           "Hexis plus reason. That was NE II’s lookFor."),
        mc(3, "First philosophy studies",
           "moving things as moving, only",
           "being qua being — with ‘being’ said in many ways around a focus (substance)",
           "only numbers",
           "only the Cave",
           "b",
           "Metaphysics I and IV openings, after the Categories’ primary substance."),
        mc(4, "Demonstration cannot go back forever because",
           "Aristotle dislikes arguments",
           "some principles must be known another way (nous / induction), or nothing is scientifically known",
           "all science is innate",
           "rhetoric is enough",
           "b",
           "Posterior Analytics I.1–3. The unit’s last sitting."),
        tf(5, "On the Categories, the species ‘human’ is more substance than Socrates.",
           "false",
           "Primary substance is the particular. That decision still governs the metaphysics sitting."),
    )
    add(
        "epicurean-garden",
        "Garden: recap",
        "Pleasure disciplined, and a physics that is already a therapy.",
        mc(1, "Epicurus’s letter and Lucretius I–III together claim that",
           "unlimited luxury is the end",
           "fear of gods and of death rests on a false physics, and empty desires cannot be satisfied",
           "the soul is immortal",
           "the city is the highest good as in Aristotle’s Politics",
           "b",
           "Ethics first (Menoeceus), then the atomic reasons (Lucretius)."),
        mc(2, "Death is nothing to us, in this school, because",
           "death is pleasant",
           "no subject remains to suffer — Book III’s dissolution of the soul-compound",
           "the unborn are miserable",
           "Stoic assent replaces physics",
           "b",
           "The letter’s slogan gets Lucretius’s argument."),
        mc(3, "Void in Lucretius I is required for",
           "the gods’ home",
           "motion and rearrangement of atoms",
           "Platonic Forms",
           "the general will",
           "b",
           "Same Eleatic pressure as the earlier atomists, now in the service of a life."),
        tf(4, "This unit’s hedonism is identical with pursuing every pleasure as it arises.",
           "false",
           "Natural vs empty desires, and pleasures that cost greater pains, are the filter."),
        mc(5, "A remaining objection the sittings asked you to keep is that",
           "Lucretius writes in Latin",
           "showing there is no post-mortem experience may not yet show that death cannot be bad as deprivation",
           "Epicurus never mentions prudence",
           "atoms cannot be named",
           "b",
           "Book III’s seminar question. Recap it, don’t erase it."),
    )
    add(
        "stoic-discipline",
        "Stoics: recap",
        "What is up to us, from handbook to notebook.",
        mc(1, "The shared Stoic cut in this unit is between",
           "Greeks and Romans",
           "what is up to us (judgment, assent) and what is not (body, office, others’ acts)",
           "pleasure and ataraxia as Epicurus ranks them",
           "Forms and particulars",
           "b",
           "Epictetus states it; Marcus applies it under an empire."),
        mc(2, "Testing impressions matters because",
           "the cosmos must change first",
           "passion follows a judgment that something not up to you is good or evil",
           "roles do not exist",
           "the handbook is only for slaves in a legal sense",
           "b",
           "Assent is the free act. Roles are duties, not a feeling of calm."),
        mc(3, "A misreading this unit refuses is that Stoicism",
           "classifies value",
           "promises that the body will not be harmed if you are wise",
           "uses spiritual exercises",
           "relocates freedom inside",
           "b",
           "Marcus still dies; Epictetus still has a body. The good is not immunity."),
        tf(4, "The Meditations are best used as a system of lemmas like Spinoza’s Ethics.",
           "false",
           "They are a notebook of repeated moves. The unit taught you to find the moves."),
        mc(5, "Compared with the Garden, the Stoic good is",
           "also a classification of desires for food",
           "located in the quality of the ruling faculty’s use, not in the atomic dissolution of fear alone",
           "identical with empty desires",
           "a proof that physics is unnecessary",
           "b",
           "That is why the era ordered Garden then Porch."),
    )
    add(
        "augustine-inwardness",
        "Augustine: recap",
        "Evil, will, and time — three inward problems, not one memoir.",
        mc(1, "Book VII’s claim about evil is that",
           "evil is a co-eternal substance",
           "evil is privation of good, against Manichaean dualism",
           "the will is already healed",
           "time is a container God sits in",
           "b",
           "Keep VII distinct from VIII. Intellect first."),
        mc(2, "Book VIII’s two wills describe",
           "two gods",
           "a divided will that cannot close itself by more information alone",
           "Aristotle’s mean as sufficient",
           "the distension of time",
           "b",
           "The garden is the drama of consent and habit, not a repeat of Platonist books."),
        mc(3, "Book XI locates time, constructively, in",
           "a heavenly clock",
           "the soul’s distension: memory, attention, expectation",
           "the Five Ways",
           "Lucretius’s atoms only",
           "b",
           "The puzzle of past and future is the opening; distension is the proposal."),
        tf(4, "These three books are interchangeable chapters on the same thesis.",
           "false",
           "Evil, will, and time are three problems. Collapsing them is the usual skim."),
        mc(5, "Relative to Plotinus, Augustine’s conversion story adds",
           "nothing inward",
           "a will and a time that Greek hypostases did not narrate as confession",
           "a denial of God",
           "the atomists’ void",
           "b",
           "The unit sits after platonic ascent for that reason."),
    )
    add(
        "aquinas-ways-and-law",
        "Aquinas: recap",
        "A science of revelation, five ways from the world, and practical reason’s first precepts.",
        mc(1, "Sacred doctrine is a science, in q.1, because it",
           "needs no revelation",
           "subalternates to a higher knowledge, as other sciences take principles from a superior",
           "replaces all philosophy",
           "is only the Five Ways",
           "b",
           "q.1 is the relation of two lights, before q.2."),
        mc(2, "The Five Ways are",
           "five ontological arguments",
           "a posteriori paths from features of the world to a first that is called God",
           "Anselm restated",
           "proofs of the Trinity",
           "b",
           "Do not inflate q.2 into the whole Summa."),
        mc(3, "Natural law’s first precept is",
           "maximize preference satisfaction",
           "good is to be done and pursued, evil avoided — specified via natural inclinations",
           "whatever the tyrant promulgates",
           "identical with physical law",
           "b",
           "q.90’s definition of law (reason, common good, competent maker, promulgation) frames q.94."),
        tf(4, "Aquinas thinks particular conclusions of natural law can never be obscured by vice or custom.",
           "false",
           "q.94 discusses just that obscuring. The first precept is not a complete code in every mind."),
        mc(5, "This unit’s order (doctrine, ways, law) teaches that",
           "ethics comes from nowhere",
           "metaphysical theology and practical reason are distinct sittings of one system",
           "Maimonides is rejected without remainder",
           "Bacon already arrived",
           "b",
           "You need q.1 to know what q.2 is doing, and both to hear law as ordinance of reason."),
    )
    add(
        "descartes-meditations",
        "Meditations: recap",
        "Doubt, God, error, essence, and the union — one arc, three sittings.",
        mc(1, "Meditations I–II secure",
           "the existence of other bodies",
           "the thinking I, after a doubt that includes dreaming and a deceiver",
           "the difference principle",
           "Locke’s blank paper",
           "b",
           "Wax is about mind’s grasp, still inside a thin ontology."),
        mc(2, "III–IV add",
           "only the wax",
           "God as cause of the idea of the infinite, and error as the will’s overreach",
           "Hobbes’s sovereign",
           "the death of God",
           "b",
           "The circularity worry (C&D guaranteed by a God proved using C&D) belongs here."),
        mc(3, "V–VI add",
           "nothing about body",
           "an ontological argument, the real distinction of mind and body, and the composite of sensation",
           "Spinoza’s one substance as Descartes’ conclusion",
           "the idols of the theatre",
           "b",
           "Dualism plus union: neither slogan is the whole of VI."),
        tf(4, "The Discourse’s provisional morale is the same sitting as Meditation VI’s union.",
           "false",
           "The Discourse was a scaffold for living; the Meditations slow the metaphysics. Different assignments."),
        mc(5, "A mistake this unit is designed to kill is that methodic doubt is",
           "an instrument for certainty",
           "a recommendation to live as a skeptic",
           "followed by a rebuilding",
           "compatible with a later divine guarantee",
           "b",
           "Doubt is a filter, not a lifestyle. Hume will later refuse this rebuild."),
    )
    add(
        "after-descartes",
        "After Descartes: recap",
        "One substance, a wager, and windowless simples — three replies.",
        mc(1, "Spinoza’s God-or-Nature, relative to Descartes, is a refusal of",
           "all necessity",
           "created finite substances and a lawgiving will that could have done otherwise",
           "geometry",
           "the word ‘God’",
           "b",
           "Modes, not rival substances. Necessity is the affect of Part I."),
        mc(2, "Pascal’s Wager is",
           "a fifth Way",
           "a practical argument under uncertainty, inside a humility about the God of the philosophers vs Abraham",
           "the cogito",
           "pre-established harmony",
           "b",
           "Do not inflate it into the whole of the Pensées, but do not treat it as a theorem either."),
        mc(3, "Leibniz’s monads and harmony are a reply to",
           "Epicurus only",
           "the mind–body union problem (and occasionalism) without influx through ‘windows’",
           "Mill’s harm principle",
           "the Cave",
           "b",
           "Best possible world is a theodicy of optimization, not a cheer."),
        tf(4, "These three authors agree that finite minds are modes of one substance.",
           "false",
           "Only Spinoza says that. Leibniz multiplies substances; Pascal is not doing Ethics I."),
        mc(5, "The unit’s pedagogical point is that",
           "Descartes ended metaphysics",
           "the Meditations’ dualism and theodicy of error immediately generate rival systems",
           "empiricism has already arrived",
           "the idols replace God",
           "b",
           "Hobbes and Locke come next as a different pressure: bodies, experience, politics."),
    )
    add(
        "political-bodies",
        "Hobbes and Locke: recap",
        "War, authorization, labor, and trust.",
        mc(1, "Hobbes’s natural condition is a war chiefly because of",
           "a few villains",
           "equality of vulnerability and a right to all that makes preemption rational",
           "Locke’s spoilage proviso",
           "the general will",
           "b",
           "Chs. 13–14. Injustice as crime waits on a sword."),
        mc(2, "Locke’s natural condition already includes",
           "no property and no law of nature",
           "a law of nature and property by labor, before the magistrate",
           "authorization of an unlimited sovereign as the first act",
           "the difference principle",
           "b",
           "That is why the unit is a disagreement, not a sequel."),
        mc(3, "Hobbesian liberty of subjects is mainly",
           "a natural right to everything remaining",
           "the silence of the law, plus defense of life",
           "a right of revolution whenever taxes exist",
           "Mill’s harm principle",
           "b",
           "Ch. 21. Locke’s ch. 19 is a different account of dissolution."),
        tf(4, "Locke treats conquest as a complete title equivalent to consent.",
           "false",
           "Consent (and trust) are the titles. Tyranny is power beyond right."),
        mc(5, "Authorization (Hobbes) vs trust (Locke) names",
           "the same legal idea",
           "whether the sovereign’s acts are yours by representation, or limited by a fiduciary end",
           "property in land only",
           "the Panopticon",
           "b",
           "Keep the two political metaphysics distinct before Hume and Rousseau."),
    )
    add(
        "ideas-and-qualities",
        "Ideas and qualities: recap",
        "No innatism, primary/secondary, then esse is percipi.",
        mc(1, "Locke’s anti-innatism claims that",
           "children know mathematics innately",
           "apparent innateness is explained by teaching and reason; universal consent is missing",
           "Descartes never used ideas",
           "secondary qualities are innate",
           "b",
           "I.2. Then II fills the paper from sensation and reflection."),
        mc(2, "Primary vs secondary qualities distinguish",
           "two kinds of Forms",
           "bulk/figure/motion as in bodies vs powers to produce color/taste that do not resemble those ideas",
           "innate vs adventitious ideas as Descartes listed them",
           "justice vs charity",
           "b",
           "II.8. Berkeley will deny the material substratum that was supposed to hold the powers."),
        mc(3, "Berkeley’s idealism keeps",
           "inert matter as Locke’s substance",
           "spirits and a God who sustains the order of ideas — not solipsism as the conclusion",
           "abstract general triangles as Locke’s theory needs them",
           "the cogito as the only spirit",
           "b",
           "The vanishing-furniture joke ignores God and laws of nature as patterns of ideas."),
        tf(4, "Personal identity in Locke II.27 is sameness of soul-substance as such.",
           "false",
           "It is sameness of consciousness, a forensic notion. Berkeley’s sitting was not that chapter, but the unit includes it."),
        mc(5, "The unit’s arc is that empiricism",
           "ends with Hobbes",
           "first fills the mind from experience, then comes under pressure about what ‘body’ can mean",
           "already includes Hume’s custom",
           "rejects all science",
           "b",
           "Hume is the next unit. Do not skip Berkeley as a joke."),
    )
    add(
        "hume-mitigated",
        "Hume: recap",
        "Ideas, causation, miracles, self, and design — one empiricism, five sittings.",
        mc(1, "The copy principle is used to",
           "prove God",
           "test whether a philosophical term has an impression — preparing the treatment of power and self",
           "establish innate ideas",
           "refute custom",
           "b",
           "§2 is not a side essay. Causation and the self inherit the test."),
        mc(2, "Causal inference, for Hume, is",
           "a demonstration",
           "custom after constant conjunction, with necessary connexion as a feeling of determination",
           "insight into a glue in objects",
           "forbidden in ordinary life",
           "b",
           "Mitigated skepticism: we live by it; we do not see into the essence of power."),
        mc(3, "Miracles as a topic of evidence depend on",
           "defining a miracle as any surprise",
           "weighing testimony against uniform experience of laws of nature",
           "the bundle self only",
           "Cleanthes’ machine analogy only",
           "b",
           "§10 is not §7. Keep the sittings."),
        mc(4, "The Treatise on personal identity and the Dialogues on design both show",
           "relations of ideas",
           "the imagination’s (or analogical reason’s) overreach beyond impressions",
           "that Berkeley was a materialist",
           "that induction is a proof",
           "b",
           "Bundle and fiction; underdetermined designer. Different objects, same discipline."),
        tf(5, "Hume’s mitigated skepticism is Pyrrhonian refusal to live by appearances.",
           "false",
           "He walks out of the study. Sextus was a different unit."),
        mc(6, "Kant will inherit from this unit especially",
           "the Five Ways",
           "the interruption of dogmatic necessity — causation as a problem for metaphysics",
           "the Panopticon",
           "double-consciousness",
           "b",
           "The Copernican preface names that interruption."),
    )
    add(
        "freedom-and-sympathy",
        "Rousseau and Smith: recap",
        "Inequality’s genealogy, the compact, and moral spectatorship.",
        mc(1, "Rousseau’s natural man, as conjecture, is",
           "Hobbes’s war as original fact",
           "independent, with pity and limited needs — moral inequality is largely historical",
           "already a voting citizen",
           "Smith’s impartial spectator",
           "b",
           "Amour-propre is social. Do not import Hobbes into the forests."),
        mc(2, "The Social Contract’s problem is",
           "how to maximize the right of the strongest",
           "a form of association that is legitimate — freedom through the general will, not force as right",
           "how to restore the Discourse’s forests as policy",
           "how to abolish all law",
           "b",
           "Will of all ≠ general will. Sovereignty ≠ government."),
        mc(3, "Smith’s TMS opening locates morals in",
           "a lonely categorical imperative",
           "sympathy and propriety — correspondence of sentiment, the seed of an impartial spectator",
           "the difference principle",
           "the slave revolt",
           "b",
           "Do not read I.i as Wealth of Nations’ ‘economic man.’"),
        tf(4, "The lawgiver in Contract II is a minor historical footnote with no paradox.",
           "false",
           "A people that needs forming cannot yet originate the laws that would form it. That was a sitting."),
        mc(5, "This unit prepares Kant by raising",
           "only property in land",
           "freedom, law, and a social origin of moral judgment — without yet a categorical imperative",
           "the copy principle",
           "monads",
           "b",
           "Kant’s Groundwork will relocate duty. Smith and Rousseau are the social-sentimental and civic-republican foils."),
    )
    add(
        "kant-copernican",
        "Kant: recap",
        "Objects conforming to cognition, then a good will and a law the will gives itself.",
        mc(1, "The Copernican turn in the first Critique’s prefaces is that",
           "astronomy replaces ethics",
           "objects of knowledge conform to our forms of knowing, so a priori knowledge of appearances is possible",
           "Hume is ignored",
           "things in themselves are known as tables",
           "b",
           "Room for faith is the other half of the limit of knowledge."),
        mc(2, "Groundwork I’s good will is good",
           "only by success",
           "without qualification, and moral worth attaches to action from duty, not merely in accordance with it",
           "when it maximizes pleasure",
           "only as a talent",
           "b",
           "The shopkeeper is the contrast case."),
        mc(3, "Groundwork II’s humanity formula forbids",
           "all cooperation",
           "treating persons merely as means — as in a lying promise that uses another’s agency",
           "all hypothetical imperatives in technical contexts",
           "autonomy as a word",
           "b",
           "Hypothetical vs categorical is the grammar; autonomy vs heteronomy is the third formula’s point."),
        tf(4, "Kant thinks the moral law is advice about what typically produces happiness.",
           "false",
           "That is prudence’s hypothetical imperative, not the CI."),
        mc(5, "Hume’s custom and Kant’s categories differ in that Kant",
           "denies all necessity",
           "relocates necessity in the subject’s way of knowing (and in practical reason’s law), rather than leaving causation as habit only",
           "repeats the copy principle",
           "accepts miracles on testimony",
           "b",
           "That is why the era ordered Hume then Kant."),
    )
    add(
        "liberty-and-utility",
        "Mill: recap",
        "Higher pleasures, harm, and individuality as a social good.",
        mc(1, "Utilitarianism ch. 2’s distinctive claim is that",
           "quantity of pleasure is all",
           "pleasures differ in kind, as competent judges who know both would prefer",
           "Kant’s good will is the standard",
           "only the agent’s pleasure counts",
           "b",
           "Socrates dissatisfied vs fool satisfied is the slogan of quality."),
        mc(2, "The harm principle limits coercion to",
           "making you virtuous for your own good as such",
           "preventing harm to others — against paternalism as a title",
           "all speech",
           "whatever custom dislikes",
           "b",
           "On Liberty I. Chapter II then defends discussion as a social good."),
        mc(3, "Individuality in ch. III is",
           "a right to injure",
           "experiments in living as a condition of human development and progress",
           "the despotism of custom under a new name",
           "the difference principle",
           "b",
           "Eccentricity is not automatically virtue; custom’s freeze is the danger."),
        tf(4, "Mill thinks silencing a false opinion costs the human race nothing.",
           "false",
           "Even a false opinion, colliding with truth, clarifies. That was ch. II."),
        mc(5, "Relative to Kant, Mill’s standard of right is",
           "the same CI",
           "the general happiness (with quality), not a formal law of maxims as the first word",
           "the right of nature",
           "ressentiment",
           "b",
           "The unit is a rival modern moral philosophy, not a footnote to the Groundwork."),
    )
    add(
        "revaluation",
        "Nietzsche: recap",
        "Two pairs of values, the animal that promises, and a dead God.",
        mc(1, "Genealogy I’s slave revolt turns",
           "good/bad into the same as good/evil",
           "noble good/bad into a resentful good/evil that brands the strong as evil",
           "Kant into Aristotle",
           "Mill’s judges into priests only",
           "b",
           "Keep the two pairs. Mixing them is the unit’s favorite error."),
        mc(2, "Genealogy II’s bad conscience is",
           "a timeless fact of reason",
           "instincts turned inward — interiority as a historical product, with guilt as a debt-story",
           "the copy principle",
           "the harm principle",
           "b",
           "The promise-making animal needed a memory made of pain first."),
        mc(3, "‘God is dead’ in the Gay Science sitting is",
           "meteorology",
           "the collapse of a horizon of meaning whose consequences are not yet absorbed",
           "Hume’s §10 only",
           "a system like the Monadology",
           "b",
           "The madman is about unreadiness, not a joke only."),
        tf(4, "Ressentiment, in Essay I, is merely a complaint with no new values.",
           "false",
           "It is creative: a new table of values. That was the lookFor."),
        mc(5, "This unit follows Marx and Kierkegaard in the era because",
           "they share a publisher",
           "history, faith’s collision with the ethical, and class struggle are already on the table — revaluation is another historical psychology",
           "Mill already said it",
           "the Cave is repeated",
           "b",
           "The nineteenth century is several hammers, not one doctrine."),
    )
    add(
        "american-pragmatism",
        "Pragmatism and Du Bois: recap",
        "Clear ideas, truth that happens, a right to believe, reconstruction, and double-consciousness.",
        mc(1, "Peirce’s maxim locates meaning in",
           "etymology",
           "conceivable practical effects of the object of the conception",
           "Cartesian innate clarity",
           "the Veil",
           "b",
           "Belief as habit of action is the setup. James will shift the accent."),
        mc(2, "James’s truth and will-to-believe, fenced correctly, are not",
           "verification and genuine options",
           "‘whatever comforts me this afternoon is true’ or ‘believe anything about the weather’",
           "a method for idle disputes",
           "live, forced, momentous options",
           "b",
           "The unit’s two James sittings are easy to parody. The fences were the assignments."),
        mc(3, "Dewey’s reconstruction asks philosophy to",
           "restore a museum of ultimate being as the first office",
           "become methods of inquiry for present problems, undoing spectator dualisms of knowing vs doing",
           "deny science",
           "repeat Moore’s open question",
           "b",
           "Then Du Bois is not an optional module: double-consciousness is a structure of knowing under the Veil."),
        mc(4, "Double-consciousness is",
           "a medical term only",
           "seeing oneself through a dominant world’s eyes — two-ness as a philosophical problem of self-knowledge",
           "Hegel’s lordship with no remainder",
           "Peirce’s maxim",
           "b",
           "The Souls sitting belongs in this unit because pragmatism without the color-line is a truncated American story."),
        tf(5, "This unit treats Du Bois as a mere illustration of James’s will to believe.",
           "false",
           "The Veil is its own analysis. Do not reduce it to a pragmatist example."),
    )
    add(
        "analytic-turn",
        "Analytic turn: recap",
        "Good as simple, sense-data, induction, pictures, and silence.",
        mc(1, "Moore’s opening move in ethics is that",
           "good = pleasure",
           "good is simple and non-natural; naturalistic identifications fail the open question",
           "only Mill remains",
           "the Tractatus already defined good as a fact",
           "b",
           "Then Russell relocates philosophy’s first problem in appearance and inference."),
        mc(2, "Russell’s table and induction sittings together claim that",
           "science is false",
           "what is immediate is not the public object, and the future is not a theorem — yet we need a principle of induction",
           "Hume should be ignored",
           "sense-data are atoms",
           "b",
           "Acquaintance vs the physical; postulate vs proof."),
        mc(3, "The Tractatus pair (picture, then silence) says that",
           "ethics is one more fact in the world",
           "sayable sense is pictorial of facts, and the rest — including the book’s own elucidations — is to be thrown away",
           "ordinary language is the first method of PI already",
           "Russell’s induction is a picture",
           "b",
           "The ladder and 7. The Investigations will be a different assignment."),
        tf(4, "This unit’s authors all treat ‘good’ as a natural property like yellow.",
           "false",
           "Moore’s point is the opposite. The Tractatus then takes ethics off the table of facts."),
        mc(5, "The pedagogical hinge into the present-day era is that",
           "the Tractatus ended philosophy",
           "picture-sense and what cannot be said set up both later Wittgenstein and the bibliographic ‘keep going’ sittings",
           "Quine already appeared",
           "Rawls is a sense-datum",
           "b",
           "1922 is a door, not a wall — but the next door is in copyright."),
    )
    add(
        "husserl",
        "Husserl: recap",
        "Psychologism, intentionality, epoché, residue — four moves, not one slogan.",
        mc(1, "The Prolegomena sitting attacks psychologism because if logic were only how we happen to think, then",
           "mathematics would be easier",
           "validity would lose its normative force and relativize to a species’ habits",
           "Heidegger would already have been answered",
           "Findlay would be public domain",
           "b",
           "Crisis of validity, not a taste in psychology."),
        mc(2, "Intentionality in Investigation V is",
           "a plan to be good",
           "consciousness as consciousness-of — aboutness primitive, even when the object does not exist as a real thing",
           "a copy-theory of ideas",
           "the cogito as a substance first",
           "b",
           "The unit’s second move. Not Descartes’ inner pictures."),
        mc(3, "The epoché in Ideas I",
           "is Sextus’s way of life under another name",
           "suspends the natural attitude’s general thesis without a skeptical denial of the world",
           "proves the world is a dream",
           "is identical with Meditation I",
           "b",
           "Third sitting. Noesis/noema then name act and intended-as-such."),
        tf(4, "§§49–50 require you to live as if physics were false.",
           "false",
           "Residue of consciousness as thesis-cancelled, not a lifestyle of dreaming. Heidegger will refuse the spectator start."),
        mc(5, "The unit’s hinge into Heidegger is that",
           "they share a publisher",
           "Husserl’s residual consciousness is a starting point Being and Time will not take — Dasein is already in-the-world",
           "both reject all phenomenology",
           "Gibson 1931 is hosted here",
           "b",
           "Read Husserl first so the Introduction is a disagreement."),
    )
    add(
        "scientific-method",
        "Scientific method: recap",
        "Falsification, web of belief, paradigms — three tools, not one calendar.",
        mc(1, "Popper’s assigned chapters replace verification, as a demarcation of science, with",
           "induction made certain",
           "falsifiability: a theory must risk clash with some possible basic statement",
           "whatever a paradigm currently teaches",
           "the analytic/synthetic cut",
           "b",
           "Ch. I and IV. Confirming instances are not enough."),
        mc(2, "Quine’s two dogmas are",
           "falsification and paradigms",
           "the analytic/synthetic distinction and reductionism of each statement to a sensory range",
           "normal science and revolution",
           "epoché and noema",
           "b",
           "Without naming the dogmas, the web has nothing to replace."),
        mc(3, "Kuhn’s normal science is",
           "perpetual revolution",
           "puzzle-solving under a paradigm, not a daily hunt for falsifying instances as the whole business",
           "identical with Hume’s custom",
           "Kant’s Copernican turn",
           "b",
           "Chs. I–III. Revolutions then change world-views (IX–X), not mere cumulative approach to one language."),
        tf(4, "The unit’s pedagogical order (Popper → Quine → Kuhn) is the same as the calendar of first publication in English.",
           "false",
           "Quine 1951 is before English LSD 1959. The professorNote: dates overlap; demarcation, then holism, then paradigms."),
        mc(5, "A tension among the three is that",
           "they share a publisher",
           "Popper wants a sharp clash with basic statements, Quine lets revision strike anywhere, Kuhn describes communities under incommensurable paradigms",
           "they all accept verificationism",
           "they all start from sense-data as Russell’s table",
           "b",
           "The recap is contrast, not a blend."),
    )
    add(
        "ethics-politics-power",
        "Justice, power, the good: recap",
        "Original position, panoptic diagram, and moral vision.",
        mc(1, "Rawls’s two principles, in order, are",
           "wealth, then speech",
           "equal basic liberties; then inequalities to the greatest benefit of the least advantaged, with fair equality of opportunity",
           "the Panopticon, then attention",
           "utility as a sum first",
           "b",
           "A device (veil), not a history. Not simple equality."),
        mc(2, "Foucault’s Panopticism describes power as",
           "only a king’s sword",
           "productive discipline via possible visibility — unlike Hobbes’s spectacular sovereign",
           "the original position",
           "Murdoch’s mother-in-law",
           "b",
           "The unit’s point is that justice-as-fairness and discipline-as-production are different tools."),
        mc(3, "Murdoch locates moral activity in",
           "a naked will’s isolated choices as the whole story",
           "attention and vision — the Good as magnetic, against existentialist will as complete",
           "the difference principle only",
           "the death of God",
           "b",
           "Unselfing is work. The Cave is a cousin, not a copy."),
        tf(4, "These three essays are three editions of the same theory.",
           "false",
           "The professorNote: none replaces the others. The recap is the contrast."),
        mc(5, "A question that joins the three without blending them is",
           "whether tables are brown",
           "what a theory of justice misses if subjects are already disciplinary, and what a theory of power misses if vision of the Good is real",
           "whether Thales said water",
           "whether the copy principle holds",
           "b",
           "The assignments’ own seminar questions. The maps come next."),
    )

    return r
